/* ============================================================
   GLOSARIO DE INGLES - datos de las entradas con pagina propia.
   Para agregar una palabra: copia una entrada, cambia los campos y
   ejecuta:  node tools/generar_glosario.js
   (genera las paginas, el indice, el sitemap y la lista de audios).

   Campos:
     slug    URL: /glosario/<slug>/
     t       termino tal como se muestra
     tipo    palabra | expresion | phrasal | diferencia | gramatica
     comun   true = tambien aparece en el filtro "Errores comunes"
     resp    respuesta corta (1-2 frases). Va en el indice y en la meta description
     pron    pronunciacion sencilla (silaba fuerte en MAYUSCULAS)
     uso     parrafos cortos ("_texto_" = cursiva)
     ej      [[ingles, espanol], ...]  (el audio lee los primeros 3)
     err     [mal, bien, nota]  (opcional)
     truco   mini truco para recordarlo (opcional)
     art     slug del articulo completo (articulo-<slug>.html), si existe
     art2    segundo articulo (opcional)
     prac    grammar | vocabulary | listening  (a donde lleva "Practicar gratis")
     rel     slugs relacionados (solo con sentido real)
     dialogo [[ingles, espanol], ...] (opcional, 2 voces, alterna A/B)
   ============================================================ */
module.exports = [
/* ---------------- PALABRAS Y EXPRESIONES ---------------- */
{ slug:'although', t:'although', tipo:'palabra',
  resp:`Aunque. Une dos ideas que chocan: _Although it was cold, we went out._`,
  pron:'ol-DÓU',
  uso:[`Se usa cuando la segunda idea es una sorpresa respecto a la primera. Puede ir al inicio de la oración (con coma) o en medio.`,
       `Después de _although_ va una oración completa, con sujeto y verbo. Si lo que sigue es solo un sustantivo, usa _despite_ o _in spite of_. Y no pongas _but_ en la misma frase: _although_ ya hace ese trabajo.`],
  ej:[[`Although it was cold, we went to the beach.`,`Aunque hacía frío, fuimos a la playa.`],[`I like him, although he talks a lot.`,`Me cae bien, aunque habla mucho.`],[`Although she studied, she failed the test.`,`Aunque estudió, reprobó el examen.`]],
  err:[`Although it was late, but I called her.`,`Although it was late, I called her.`,`Con although no se usa but en la misma oración.`],
  truco:`Piensa en "aunque". Si ya dijiste aunque, no necesitas decir "pero" otra vez.`,
  prac:'grammar', rel:['even-though','however','instead-of'] },

{ slug:'already', t:'already', tipo:'palabra',
  resp:`Ya. Algo ya pasó o ya está hecho, a veces antes de lo esperado: _I have already eaten._`,
  pron:'ol-RÉ-di',
  uso:[`Se usa sobre todo en oraciones afirmativas. Suele ir entre el auxiliar y el verbo (_have already eaten_) o al final de la frase.`,
       `En preguntas puede mostrar sorpresa (_Is it ten already?_). En negativas no se usa _already_: se usa _yet_.`,
       `Ojo: _all ready_ (dos palabras) significa "todos listos": _We are all ready to go._`],
  ej:[[`I have already eaten.`,`Ya comí.`],[`She already knows the answer.`,`Ella ya sabe la respuesta.`],[`Is it ten o'clock already?`,`¿Ya son las diez?`]],
  err:[`I haven't finished already.`,`I haven't finished yet.`,`En negativas va yet, no already.`],
  truco:`Already = ya está hecho. Yet = todavía no (o "¿ya?" en preguntas).`,
  art:'presente-perfecto', prac:'grammar', rel:['yet','still'] },

{ slug:'get', t:'get', tipo:'palabra',
  resp:`Conseguir, recibir, llegar o ponerse. Es uno de los verbos más usados y cambia según lo que lo acompaña.`,
  pron:'GUÉT',
  uso:[`Mira qué viene después. _Get_ + cosa = conseguir o recibir (_I got a new phone_). _Get_ + lugar = llegar (_We got home late_). _Get_ + adjetivo = ponerse o volverse (_She got angry_).`,
       `También significa "entender" en conversación: _I don't get it._ Y forma muchos phrasal verbs: _get up_ (levantarse), _get on_ (subir), _get off_ (bajar).`,
       `Pasado: _got_. En inglés de Estados Unidos, el participio suele ser _gotten_: _I've gotten better._`],
  ej:[[`I got a message from Leo.`,`Recibí un mensaje de Leo.`],[`What time do you get home?`,`¿A qué hora llegas a casa?`],[`It's getting dark.`,`Está oscureciendo.`],[`I don't get it.`,`No lo entiendo.`]],
  truco:`Fíjate en la palabra que sigue: lugar = llegar, adjetivo = ponerse, cosa = conseguir o recibir.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['look-for','find-out','give-up'] },

{ slug:'would-rather', t:'would rather', tipo:'expresion',
  resp:`Preferiría. Dice lo que preferirías hacer: _I'd rather stay home._`,
  pron:'uud RÁ-der',
  uso:[`Estructura: _would rather_ + verbo en forma base, sin _to_. Se contrae como _I'd rather_. Para negar: _would rather not_ + verbo.`,
       `Para comparar: _would rather A than B_. Y si hablas de lo que quieres que otra persona haga, el verbo siguiente va en pasado: _I'd rather you stayed here._`],
  ej:[[`I'd rather stay home tonight.`,`Preferiría quedarme en casa esta noche.`],[`She'd rather not go.`,`Ella preferiría no ir.`],[`I'd rather walk than take the bus.`,`Prefiero caminar que tomar el bus.`]],
  err:[`I'd rather to stay.`,`I'd rather stay.`,`Después de would rather el verbo va sin to.`],
  truco:`Would rather funciona como can o should: el verbo que sigue va en forma base.`,
  prac:'grammar', rel:['should-have','instead-of','used-to'],
  dialogo:[[`Do you want to go out tonight?`,`¿Quieres salir esta noche?`],[`I'd rather stay home. I'm tired.`,`Preferiría quedarme en casa. Estoy cansado.`],[`Would you rather watch a movie or order pizza?`,`¿Preferirías ver una película o pedir pizza?`],[`I'd rather do both.`,`Preferiría hacer las dos cosas.`]] },

{ slug:'used-to', t:'used to', tipo:'expresion', comun:true,
  resp:`Antes, solía. Habla de algo que pasaba en el pasado y ya no: _I used to live there._`,
  pron:'IÚST tu',
  uso:[`_Used to_ + verbo en forma base habla de hábitos o situaciones del pasado que ya no son así.`,
       `En preguntas y negaciones se escribe _use to_, sin d: _Did you use to...?_, _I didn't use to..._`,
       `No lo confundas con _be used to_ + -ing, que significa "estar acostumbrado": _I'm used to waking up early._`],
  ej:[[`I used to play soccer every weekend.`,`Antes jugaba fútbol todos los fines de semana.`],[`We didn't use to have a car.`,`Antes no teníamos carro.`],[`I'm used to the cold.`,`Estoy acostumbrado al frío.`]],
  err:[`Did you used to live here?`,`Did you use to live here?`,`Con did, used pierde la d: use to.`],
  truco:`Used to = antes sí, ahora no. Be used to = ya me acostumbré.`,
  art:'errores-comunes', prac:'grammar', rel:['would-rather','still'] },

{ slug:'should-have', t:'should have', tipo:'expresion', comun:true,
  resp:`Debería haber, debí. Lamenta o critica algo que no pasó: _I should have called._`,
  pron:'SHÚ-da (rápido)',
  uso:[`Estructura: _should have_ + participio. Habla del pasado y dice qué habría sido mejor hacer. En negativo, _shouldn't have_ + participio: "no debí haberlo hecho".`,
       `Se contrae _should've_. En habla rápida suena como "shuda", y por eso mucha gente lo escribe mal como _should of_. Lo correcto es _should have_.`],
  ej:[[`I should have studied more.`,`Debí estudiar más.`],[`You shouldn't have said that.`,`No debiste decir eso.`],[`We should have left earlier.`,`Deberíamos haber salido antes.`]],
  err:[`I should of called you.`,`I should have called you.`,`Es have (o should've), nunca of.`],
  truco:`Should + have + participio: miras hacia atrás en el tiempo.`,
  prac:'grammar', rel:['would-rather','used-to'],
  dialogo:[[`I missed the bus again.`,`Perdí el bus otra vez.`],[`You should have left earlier.`,`Debiste salir más temprano.`],[`I know. I should have set an alarm.`,`Lo sé. Debí poner una alarma.`],[`Next time, you will.`,`La próxima vez lo harás.`]] },

{ slug:'look-for', t:'look for', tipo:'phrasal',
  resp:`Buscar. Intentas encontrar algo o a alguien: _I'm looking for my keys._`,
  pron:'LUK for',
  uso:[`_Look for_ + lo que buscas. No se separa y no lleva otra preposición.`,
       `Compáralo: _look at_ = mirar, _look for_ = buscar, _find_ = encontrar (ya lo tienes).`],
  ej:[[`I'm looking for my keys.`,`Estoy buscando mis llaves.`],[`She is looking for a new job.`,`Ella está buscando un trabajo nuevo.`],[`What are you looking for?`,`¿Qué estás buscando?`]],
  err:[`I'm looking my keys.`,`I'm looking for my keys.`,`Sin for, look no significa buscar.`],
  truco:`look at = mirar, look for = buscar, find = encontrar.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['find-out','give-up','get'] },

{ slug:'give-up', t:'give up', tipo:'phrasal',
  resp:`Rendirse, o dejar de hacer algo: _Don't give up!_`,
  pron:'GUIV ap',
  uso:[`Puede ir sola (_give up_ = rendirse) o con algo: _give up smoking_ (dejar de fumar). Después de _give up_, el verbo va con -ing.`,
       `Es separable: _give it up_. Con un pronombre, va en medio: _give it up_, no _give up it_.`],
  ej:[[`Don't give up. You're almost there.`,`No te rindas. Ya casi llegas.`],[`He gave up smoking last year.`,`Dejó de fumar el año pasado.`],[`I give up! What's the answer?`,`¡Me rindo! ¿Cuál es la respuesta?`]],
  err:[`He gave up to smoke.`,`He gave up smoking.`,`Después de give up va -ing.`],
  truco:`Give up + -ing: dejar un hábito. Give up solo: rendirse.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['look-for','find-out'] },

{ slug:'find-out', t:'find out', tipo:'phrasal',
  resp:`Averiguar, enterarse. Descubres información que no sabías: _I found out the truth._`,
  pron:'FAIND aut',
  uso:[`_Find out_ habla de información: descubrir un dato. _Find_ habla de encontrar algo concreto, como unas llaves.`,
       `Suele ir seguido de _that, what, who, when, if_: _I need to find out when the store opens._`],
  ej:[[`I need to find out what time it starts.`,`Necesito averiguar a qué hora empieza.`],[`She found out that he was lying.`,`Ella se enteró de que él mentía.`],[`Let me find out and I'll call you back.`,`Déjame averiguar y te llamo.`]],
  err:[`I found out my keys.`,`I found my keys.`,`Para cosas concretas usa find, no find out.`],
  truco:`find = encuentras una cosa. find out = encuentras la información.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['look-for','give-up'] },

{ slug:'look-forward-to', t:'look forward to', tipo:'expresion',
  resp:`Tener ganas de, esperar con ilusión: _I look forward to meeting you._`,
  pron:'LUK FÓR-uerd tu',
  uso:[`Aquí _to_ es una preposición, así que después va un sustantivo o un verbo con -ing, no el verbo base.`,
       `Es muy común en correos formales: _I look forward to hearing from you._`],
  ej:[[`I'm looking forward to the weekend.`,`Tengo muchas ganas de que llegue el fin de semana.`],[`We look forward to seeing you.`,`Esperamos verte pronto.`],[`She is looking forward to her trip.`,`Ella espera su viaje con ilusión.`]],
  err:[`I look forward to see you.`,`I look forward to seeing you.`,`Después de forward to va -ing.`],
  truco:`Después de look forward to, piensa en -ing.`,
  art:'correo-formal-en-ingles', prac:'grammar', rel:['used-to'] },

{ slug:'however', t:'however', tipo:'palabra',
  resp:`Sin embargo. Une dos ideas con contraste y suena más formal que _but_.`,
  pron:'jau-É-ver',
  uso:[`_However_ suele empezar una oración nueva, con coma después: _It was cheap. However, it was bad._ También puede ir después de punto y coma.`,
       `_But_ va en medio de una oración. _However_ no se pega con una coma entre dos ideas: eso es un error frecuente.`],
  ej:[[`The hotel was nice. However, it was far from the center.`,`El hotel era bonito. Sin embargo, estaba lejos del centro.`],[`I wanted to go; however, I had to work.`,`Quería ir; sin embargo, tenía que trabajar.`]],
  err:[`It was cheap, however it was bad.`,`It was cheap. However, it was bad.`,`Antes de however va punto o punto y coma, no solo coma.`],
  truco:`However = otra oración que contradice la anterior.`,
  art:'correo-formal-en-ingles', prac:'vocabulary', rel:['although','even-though'] },

{ slug:'actually', t:'actually', tipo:'palabra', comun:true,
  resp:`En realidad, de hecho. No significa "actualmente".`,
  pron:'ÁK-chua-li',
  uso:[`_Actually_ sirve para corregir algo o dar un dato que sorprende. Se parece a "actualmente", pero es un falso amigo.`,
       `"Actualmente" en inglés es _currently_ o _at the moment_.`],
  ej:[[`Actually, I'm from Colombia, not Mexico.`,`En realidad, soy de Colombia, no de México.`],[`I actually liked the movie.`,`De hecho, me gustó la película.`],[`I'm currently studying English.`,`Actualmente estudio inglés.`]],
  err:[`Actually I work in Madrid. (quería decir "actualmente")`,`Currently I work in Madrid.`,`Actually = en realidad; currently = ahora.`],
  truco:`actually = en realidad. currently = ahora.`,
  prac:'vocabulary', rel:[] },

{ slug:'even-though', t:'even though', tipo:'expresion',
  resp:`Aunque, a pesar de que. Es una versión más fuerte de _although_ para hechos reales.`,
  pron:'Í-ven DÓU',
  uso:[`_Even though_ + oración completa. Habla de algo que sí es real y que contrasta con lo otro.`,
       `_Even if_ es distinto: habla de algo que podría pasar. _Even if it rains, we'll go._`],
  ej:[[`Even though he was tired, he kept working.`,`Aunque estaba cansado, siguió trabajando.`],[`I went to work even though I was sick.`,`Fui a trabajar aunque estaba enfermo.`],[`Even if it rains, we'll go.`,`Aunque llueva, iremos.`]],
  err:[`Even though of the traffic, I arrived on time.`,`Even though there was traffic, I arrived on time.`,`Después de even though va sujeto + verbo.`],
  truco:`even though = ya pasó o es real. even if = tal vez pase.`,
  prac:'grammar', rel:['although','however'] },

{ slug:'instead-of', t:'instead of', tipo:'expresion',
  resp:`En lugar de, en vez de. Dice lo que eliges o haces en vez de otra cosa.`,
  pron:'in-STÉD ov',
  uso:[`_Instead of_ + sustantivo o verbo con -ing. _Instead_ sola cierra la frase o va al inicio: _I didn't call. I wrote instead._`],
  ej:[[`Let's walk instead of taking the bus.`,`Caminemos en vez de tomar el bus.`],[`I'll have water instead of soda.`,`Tomaré agua en lugar de refresco.`],[`I didn't call her. I wrote to her instead.`,`No la llamé. Le escribí en su lugar.`]],
  err:[`Let's walk instead to take the bus.`,`Let's walk instead of taking the bus.`,`Después de instead of va -ing.`],
  truco:`Instead of + -ing. Instead sola = "en cambio".`,
  prac:'grammar', rel:['would-rather','although'] },

{ slug:'yet', t:'yet', tipo:'palabra',
  resp:`Todavía (no) o ya (en preguntas). Se usa en negativas y preguntas, casi siempre al final.`,
  pron:'IÉT',
  uso:[`Negativa: _I haven't finished yet_ (todavía no terminé). Pregunta: _Have you finished yet?_ (¿ya terminaste?).`,
       `En afirmativas no se usa _yet_ con este sentido: ahí va _already_.`],
  ej:[[`I haven't seen that movie yet.`,`Todavía no he visto esa película.`],[`Has she called yet?`,`¿Ya llamó?`],[`Not yet.`,`Todavía no.`]],
  err:[`I have finished yet.`,`I have already finished.`,`En afirmativas se usa already, no yet.`],
  truco:`yet = esperas que pase. already = ya pasó.`,
  art:'presente-perfecto', prac:'grammar', rel:['already','still'] },

{ slug:'still', t:'still', tipo:'palabra',
  resp:`Todavía, aún. Algo sigue igual y no ha cambiado.`,
  pron:'STIL',
  uso:[`_Still_ va antes del verbo principal, pero después de _to be_: _I still live here_, _She is still here_.`,
       `En negativas va antes del auxiliar: _I still haven't called._ No lo confundas con _yet_: _still_ = sigue pasando; _yet_ = esperas que pase.`],
  ej:[[`I still love pizza.`,`Todavía me encanta la pizza.`],[`Are you still working?`,`¿Sigues trabajando?`],[`He still doesn't know.`,`Él todavía no sabe.`]],
  err:[`I live still here.`,`I still live here.`,`Still va antes del verbo, no al final.`],
  truco:`still = sigue igual.`,
  prac:'grammar', rel:['already','yet'] },

{ slug:'enough', t:'enough', tipo:'palabra',
  resp:`Suficiente, bastante. Cambia de lugar: antes de un sustantivo, después de un adjetivo.`,
  pron:'i-NÁF',
  uso:[`Con sustantivos va antes: _enough money_. Con adjetivos y adverbios va después: _tall enough_.`,
       `Puede seguir _to_ + verbo: _old enough to drive_.`],
  ej:[[`We have enough time.`,`Tenemos suficiente tiempo.`],[`She isn't old enough to drive.`,`Ella no tiene edad suficiente para manejar.`],[`Is it big enough?`,`¿Es lo bastante grande?`]],
  err:[`She is enough tall.`,`She is tall enough.`,`Con adjetivos, enough va después.`],
  truco:`Cosas: enough antes. Cualidades: enough después.`,
  prac:'grammar', rel:[] },

/* ---------------- DIFERENCIAS ---------------- */
{ slug:'since-vs-for', t:'since vs for', tipo:'diferencia',
  resp:`Since = desde (el momento en que empezó). For = durante (cuánto tiempo).`,
  pron:'SINS / FOR',
  uso:[`_Since_ + un punto en el tiempo: _since 2020_, _since Monday_, _since I was a child_. _For_ + una duración: _for two years_, _for three hours_.`,
       `Los dos suelen ir con presente perfecto: _I have lived here since 2020_ es lo mismo que _I have lived here for five years_.`],
  ej:[[`I have lived here since 2020.`,`Vivo aquí desde 2020.`],[`I have lived here for five years.`,`Vivo aquí desde hace cinco años.`],[`She has worked here since June.`,`Ella trabaja aquí desde junio.`]],
  err:[`I have lived here since five years.`,`I have lived here for five years.`,`Una cantidad de tiempo va con for.`],
  truco:`¿Puedes contarlo (dos años, tres horas)? For. ¿Es una fecha o un momento? Since.`,
  art:'presente-perfecto', prac:'grammar', rel:['already','yet'] },

{ slug:'make-vs-do', t:'make vs do', tipo:'diferencia', comun:true,
  resp:`Make = crear o producir algo. Do = hacer una tarea, acción o actividad.`,
  pron:'MEIK / DU',
  uso:[`_Make_ crea algo que antes no existía: _make a cake_, _make a plan_, _make a mistake_, _make money_, _make a decision_.`,
       `_Do_ habla de tareas y actividades: _do homework_, _do the dishes_, _do your best_, _do a favor_. Muchas combinaciones son fijas: conviene aprenderlas juntas.`],
  ej:[[`I made breakfast for everyone.`,`Preparé el desayuno para todos.`],[`I did my homework after dinner.`,`Hice mi tarea después de cenar.`],[`She made a mistake.`,`Ella cometió un error.`],[`Can you do me a favor?`,`¿Me haces un favor?`]],
  err:[`I did a mistake.`,`I made a mistake.`,`Mistake va con make.`],
  truco:`Make = el resultado es algo nuevo. Do = una tarea que se hace.`,
  art:'errores-comunes', prac:'vocabulary', rel:['say-vs-tell','hear-vs-listen'] },

{ slug:'hear-vs-listen', t:'hear vs listen', tipo:'diferencia',
  resp:`Hear = oír, sin querer. Listen = escuchar con atención y a propósito.`,
  pron:'JIR / LÍ-sen',
  uso:[`_Hear_ no lleva preposición: _I hear music_. _Listen_ va con _to_: _I listen to music_. En _listen_ la t no se pronuncia.`,
       `_Hear_ pasa solo; _listen_ es algo que decides hacer.`],
  ej:[[`I can hear the neighbors.`,`Oigo a los vecinos.`],[`Please listen to me.`,`Por favor, escúchame.`],[`I heard a noise outside.`,`Oí un ruido afuera.`]],
  err:[`I listen music every day.`,`I listen to music every day.`,`Listen siempre lleva to.`],
  truco:`listen to: siempre con to. hear: sin to.`,
  prac:'listening', rel:['make-vs-do'] },

{ slug:'person-vs-people', t:'person vs people', tipo:'diferencia', comun:true,
  resp:`Person = una persona. People = varias personas, y ya es plural.`,
  pron:'PÉR-sen / PÍ-pol',
  uso:[`_People_ es el plural normal de _person_ y lleva verbo en plural: _People are..._ _Persons_ existe, pero solo en textos legales; en la vida diaria se usa _people_.`,
       `_Peoples_ (con s) significa "pueblos" o "naciones".`],
  ej:[[`She is a nice person.`,`Ella es una buena persona.`],[`Many people speak English.`,`Mucha gente habla inglés.`],[`Three people are waiting outside.`,`Tres personas esperan afuera.`]],
  err:[`The people is here.`,`The people are here.`,`People es plural: va con are.`],
  truco:`people ya es plural: no le agregues -s.`,
  prac:'grammar', rel:['much-vs-many'] },

{ slug:'was-vs-were', t:'was vs were', tipo:'diferencia', comun:true,
  resp:`Was = fui, era, estaba (I, he, she, it). Were = fuiste, fueron, estaban (you, we, they).`,
  pron:'UAS / UER',
  uso:[`Son el pasado de _to be_. _Was_ va con _I, he, she, it_. _Were_ va con _you, we, they_. Con _you_ siempre es _were_, aunque hables con una sola persona.`,
       `Negativo: _wasn't_ y _weren't_. Pregunta: _Was he...?_ _Were they...?_ En frases como _If I were you_, se usa _were_ incluso con _I_.`],
  ej:[[`I was at home yesterday.`,`Ayer estuve en casa.`],[`They were very tired.`,`Ellos estaban muy cansados.`],[`Were you at the party?`,`¿Estuviste en la fiesta?`]],
  err:[`You was late.`,`You were late.`,`You siempre lleva were.`],
  truco:`Was solo con I, he, she, it. Todo lo demás: were.`,
  art:'verbo-to-be', art2:'pasado-simple', prac:'grammar', rel:['much-vs-many'] },

{ slug:'much-vs-many', t:'much vs many', tipo:'diferencia',
  resp:`Many = con cosas que se cuentan (plural). Much = con cosas que no se cuentan.`,
  pron:'MACH / MÉ-ni',
  uso:[`_Many_ + sustantivo contable en plural: _many friends_. _Much_ + sustantivo incontable: _much water_, _much time_.`,
       `Se usan sobre todo en preguntas y negativas. En afirmativas suena más natural _a lot of_: _I have a lot of friends._`],
  ej:[[`How many people are coming?`,`¿Cuántas personas vienen?`],[`I don't have much time.`,`No tengo mucho tiempo.`],[`There aren't many chairs.`,`No hay muchas sillas.`]],
  err:[`How much people are there?`,`How many people are there?`,`People se cuenta: many.`],
  truco:`¿Puedes contarlos uno por uno? Many. ¿Es una masa, como agua o tiempo? Much.`,
  prac:'grammar', rel:['fewer-vs-less','person-vs-people'] },

{ slug:'a-vs-an', t:'a vs an', tipo:'diferencia',
  resp:`An va antes de un sonido de vocal. A va antes de un sonido de consonante.`,
  pron:'a (corto) / AN',
  uso:[`Importa el sonido, no la letra. _An hour_ (la h no suena) y _a university_ (suena "iu", como consonante).`,
       `Para decidir, di la palabra en voz alta y escucha cómo empieza.`],
  ej:[[`She is an engineer.`,`Ella es ingeniera.`],[`I need an umbrella.`,`Necesito un paraguas.`],[`He goes to a university in Texas.`,`Él va a una universidad en Texas.`],[`We waited for an hour.`,`Esperamos una hora.`]],
  err:[`I have an university degree.`,`I have a university degree.`,`University empieza con sonido "iu": a.`],
  truco:`Escucha la primera palabra: ¿suena a vocal? An. ¿A consonante? A.`,
  prac:'grammar', rel:[] },

{ slug:'say-vs-tell', t:'say vs tell', tipo:'diferencia',
  resp:`Say = decir las palabras. Tell = decirle algo a alguien (lleva la persona).`,
  pron:'SEI / TEL',
  uso:[`_Tell_ va con la persona: _tell me_, _tell her_. _Say_ va con lo que se dice: _say hello_. Si quieres nombrar a la persona con _say_, necesitas _to_: _say to me_.`,
       `Combinaciones fijas: _tell the truth_, _tell a lie_, _tell a story_; _say goodbye_, _say sorry_.`],
  ej:[[`She said she was tired.`,`Ella dijo que estaba cansada.`],[`She told me she was tired.`,`Ella me dijo que estaba cansada.`],[`Tell me the truth.`,`Dime la verdad.`]],
  err:[`He said me a secret.`,`He told me a secret.`,`Con una persona directa, usa tell.`],
  truco:`tell + persona. say + palabras.`,
  prac:'grammar', rel:['make-vs-do','hear-vs-listen'] },

{ slug:'borrow-vs-lend', t:'borrow vs lend', tipo:'diferencia',
  resp:`Borrow = pedir prestado (tú recibes). Lend = prestar (tú das).`,
  pron:'BÓ-rou / LEND',
  uso:[`Si recibes algo por un tiempo: _borrow_. Si lo das por un tiempo: _lend_. El pasado de _lend_ es _lent_.`,
       `_Can I borrow your pen?_ y _Can you lend me your pen?_ piden lo mismo desde lados distintos.`],
  ej:[[`Can I borrow your charger?`,`¿Me prestas tu cargador?`],[`Could you lend me ten dollars?`,`¿Podrías prestarme diez dólares?`],[`I lent her my book.`,`Le presté mi libro.`]],
  err:[`Can you borrow me your pen?`,`Can you lend me your pen?`,`Quien da el objeto lo presta: lend.`],
  truco:`borrow = lo recibo. lend = lo doy.`,
  prac:'grammar', rel:['bring-vs-take'] },

{ slug:'bring-vs-take', t:'bring vs take', tipo:'diferencia',
  resp:`Bring = traer (hacia donde está quien habla). Take = llevar (hacia otro lugar).`,
  pron:'BRING / TEIK',
  uso:[`_Bring_ va hacia el lugar donde estás tú o donde estará quien escucha. _Take_ va hacia otro lugar, lejos de ti.`,
       `Pasados: _brought_ y _took_.`],
  ej:[[`Please bring your passport tomorrow.`,`Por favor, trae tu pasaporte mañana.`],[`I take my son to school every day.`,`Llevo a mi hijo a la escuela todos los días.`],[`Can you bring me a glass of water?`,`¿Me traes un vaso de agua?`]],
  err:[`Take me a glass of water, please.`,`Bring me a glass of water, please.`,`Hacia mí: bring.`],
  truco:`bring = hacia aquí. take = hacia allá.`,
  prac:'grammar', rel:['borrow-vs-lend'] },

{ slug:'affect-vs-effect', t:'affect vs effect', tipo:'diferencia', comun:true,
  resp:`Affect = verbo (afectar). Effect = sustantivo (efecto).`,
  pron:'a-FÉKT / i-FÉKT',
  uso:[`La mayoría de las veces, _affect_ es la acción y _effect_ es el resultado: _The weather affects my mood_ y _The weather has an effect on my mood_.`,
       `Hay usos raros al revés, pero no hacen falta para hablar o escribir en el día a día.`],
  ej:[[`The rain affected our plans.`,`La lluvia afectó nuestros planes.`],[`The medicine had a good effect.`,`La medicina tuvo un buen efecto.`],[`Stress can affect your sleep.`,`El estrés puede afectar tu sueño.`]],
  err:[`The rain effected my plans.`,`The rain affected my plans.`,`Como verbo, normalmente es affect.`],
  truco:`affect = acción. effect = efecto (el resultado).`,
  prac:'vocabulary', rel:[] },

{ slug:'fewer-vs-less', t:'fewer vs less', tipo:'diferencia',
  resp:`Fewer = menos (cosas que se cuentan). Less = menos (cosas que no se cuentan).`,
  pron:'FIÚ-er / LES',
  uso:[`_Fewer cars_ (los carros se cuentan), _less traffic_ (el tráfico no se cuenta).`,
       `En la conversación mucha gente dice _less_ para todo, pero en exámenes y textos formales se espera _fewer_ con cosas que se cuentan.`],
  ej:[[`I have fewer problems now.`,`Ahora tengo menos problemas.`],[`Drink less coffee.`,`Toma menos café.`],[`There are fewer people today.`,`Hay menos gente hoy.`]],
  err:[`There are less people today.`,`There are fewer people today.`,`People se cuenta: fewer (en formal).`],
  truco:`fewer = cuento. less = no cuento.`,
  prac:'grammar', rel:['much-vs-many'] },

{ slug:'its-vs-it-s', t:`its vs it's`, tipo:'diferencia', comun:true,
  resp:`It's = it is o it has. Its = de él, de ella, de eso (posesivo).`,
  pron:'ITS / ITS (suenan igual)',
  uso:[`_It's_ lleva apóstrofe porque es una contracción: _it is_ o _it has_. _Its_, sin apóstrofe, indica que algo le pertenece: _The dog wagged its tail._`,
       `Prueba rápida: cambia la palabra por _it is_. Si la frase sigue teniendo sentido, escribe _it's_.`],
  ej:[[`It's a beautiful day.`,`Es un día hermoso.`],[`The cat licked its paw.`,`El gato se lamió la pata.`],[`It's been a long week.`,`Ha sido una semana larga.`]],
  err:[`The company changed it's name.`,`The company changed its name.`,`Aquí es posesivo: its, sin apóstrofe.`],
  truco:`Cámbialo por "it is". ¿Funciona? Es it's.`,
  prac:'grammar', rel:['their-there-theyre','your-vs-youre'] },

{ slug:'then-vs-than', t:'then vs than', tipo:'diferencia', comun:true,
  resp:`Then = entonces, luego (tiempo). Than = que (para comparar).`,
  pron:'DEN / DAN',
  uso:[`_Then_ habla de orden o de consecuencia: _First we ate, then we left._ _Than_ aparece después de un comparativo: _taller than_, _more than_.`],
  ej:[[`She is taller than me.`,`Ella es más alta que yo.`],[`Finish your homework, then you can play.`,`Termina tu tarea, luego puedes jugar.`],[`If you're tired, then rest.`,`Si estás cansado, entonces descansa.`]],
  err:[`She is older then me.`,`She is older than me.`,`Para comparar se usa than.`],
  truco:`then = tiempo. than = comparación.`,
  prac:'grammar', rel:['its-vs-it-s'] },

{ slug:'their-there-theyre', t:`their / there / they're`, tipo:'diferencia', comun:true,
  resp:`Their = de ellos. There = allí o hay. They're = they are.`,
  pron:'DER (las tres suenan casi igual)',
  uso:[`_Their_ indica posesión: _their house_. _There_ indica lugar o existencia: _over there_, _there is a problem_. _They're_ es la contracción de _they are_.`,
       `Prueba: cambia por _they are_. Si funciona, es _they're_.`],
  ej:[[`Their house is big.`,`Su casa es grande.`],[`Put it over there.`,`Ponlo allá.`],[`They're my friends.`,`Ellos son mis amigos.`]],
  err:[`Their going home.`,`They're going home.`,`Aquí es they are: they're.`],
  truco:`their = de ellos. there = lugar. they're = they are.`,
  prac:'grammar', rel:['its-vs-it-s','your-vs-youre'] },

{ slug:'your-vs-youre', t:`your vs you're`, tipo:'diferencia', comun:true,
  resp:`Your = tu, tus. You're = you are (tú eres, tú estás).`,
  pron:'YOR / YOR (suenan casi igual)',
  uso:[`_Your_ va antes de un sustantivo: _your phone_. _You're_ es una contracción: _you are_.`,
       `El error más famoso: _Your welcome_. Lo correcto es _You're welcome_ ("de nada").`],
  ej:[[`Your phone is ringing.`,`Tu teléfono está sonando.`],[`You're late.`,`Llegas tarde.`],[`You're welcome.`,`De nada.`]],
  err:[`Your welcome.`,`You're welcome.`,`Es you are welcome: you're.`],
  truco:`Cámbialo por "you are". ¿Funciona? Es you're.`,
  prac:'grammar', rel:['its-vs-it-s','their-there-theyre'] },

{ slug:'lose-vs-loose', t:'lose vs loose', tipo:'diferencia', comun:true,
  resp:`Lose = perder (verbo). Loose = suelto, flojo (adjetivo).`,
  pron:'LUUZ / LUUS',
  uso:[`_Lose_ es un verbo: _lose a game_, _lose your keys_. Su pasado es _lost_. _Loose_ describe algo que no está apretado: _a loose shirt_.`,
       `Cuidado con la pronunciación: _lose_ termina en sonido "z" y _loose_ en sonido "s".`],
  ej:[[`I don't want to lose my job.`,`No quiero perder mi trabajo.`],[`This shirt is too loose.`,`Esta camisa está muy suelta.`],[`We lost the game.`,`Perdimos el partido.`]],
  err:[`I don't want to loose my keys.`,`I don't want to lose my keys.`,`El verbo perder es lose.`],
  truco:`lose pierde una o. loose tiene una o de más: suelto, con espacio.`,
  prac:'vocabulary', rel:[] },

{ slug:'good-vs-well', t:'good vs well', tipo:'diferencia', comun:true,
  resp:`Good = bueno (adjetivo). Well = bien (adverbio, cómo haces algo).`,
  pron:'GUD / UEL',
  uso:[`_Good_ describe personas o cosas: _a good teacher_. _Well_ describe cómo se hace algo: _She sings well._`,
       `_Well_ también puede significar "sano": _I don't feel well._`],
  ej:[[`He is a good player.`,`Él es un buen jugador.`],[`He plays well.`,`Él juega bien.`],[`I'm not feeling well.`,`No me siento bien (de salud).`]],
  err:[`She sings very good.`,`She sings very well.`,`Para decir cómo canta, usa well.`],
  truco:`good = nombre (a good friend). well = acción (works well).`,
  prac:'grammar', rel:[] },

{ slug:'as-vs-like', t:'as vs like', tipo:'diferencia',
  resp:`Like = como, parecido a. As = como, en el papel o función de.`,
  pron:'AS / LAIK',
  uso:[`_Like_ compara cosas parecidas: _She sings like a pro_ (canta como una profesional, aunque no lo es). _As_ dice qué función cumple algo o alguien: _She works as a teacher_ (es profesora).`],
  ej:[[`He runs like the wind.`,`Corre como el viento.`],[`I work as a nurse.`,`Trabajo como enfermera.`],[`Do it as I showed you.`,`Hazlo como te mostré.`]],
  err:[`I work like a waiter. (y sí eres mesero)`,`I work as a waiter.`,`Si es tu trabajo real, usa as.`],
  truco:`as = lo que es. like = parecido a.`,
  prac:'grammar', rel:[] }
];
