/* ============================================================
   GLOSARIO DE INGLES - datos de las entradas con pagina propia.
   Para agregar una palabra: copia una entrada, cambia los campos y
   ejecuta:  node tools/generar_glosario.js
   (genera las paginas, el indice, el sitemap y la lista de audios).

   Campos:
     slug    URL: /glosario/<slug>/
     t       termino tal como se muestra
     tipo    palabra | expresion | phrasal | diferencia | gramatica
     comun   true = tambien aparece en el filtro "Errores comunes"
     resp    respuesta corta (1-2 frases). Va en el indice y en la meta description
     pron    pronunciacion sencilla (silaba fuerte en MAYUSCULAS)
     uso     parrafos cortos ("_texto_" = cursiva)
     ej      [[ingles, espanol], ...]  (el audio lee los primeros 3)
     err     [mal, bien, nota]  (opcional)
     truco   mini truco para recordarlo (opcional)
     art     slug del articulo completo (articulo-<slug>.html), si existe
     art2    segundo articulo (opcional)
     prac    grammar | vocabulary | listening  (a donde lleva "Practicar gratis")
     rel     slugs relacionados (solo con sentido real)
     dialogo [[ingles, espanol], ...] (opcional, 2 voces, alterna A/B)
   ============================================================ */
module.exports = [
/* ---------------- PALABRAS Y EXPRESIONES ---------------- */
{ slug:'although', t:'although', tipo:'palabra',
  resp:`Aunque. Une dos ideas que chocan: _Although it was cold, we went out._`,
  pron:'ol-DÓU',
  uso:[`Se usa cuando la segunda idea es una sorpresa respecto a la primera. Puede ir al inicio de la oración (con coma) o en medio.`,
       `Después de _although_ va una oración completa, con sujeto y verbo. Si lo que sigue es solo un sustantivo, usa _despite_ o _in spite of_. Y no pongas _but_ en la misma frase: _although_ ya hace ese trabajo.`],
  ej:[[`Although it was cold, we went to the beach.`,`Aunque hacía frío, fuimos a la playa.`],[`I like him, although he talks a lot.`,`Me cae bien, aunque habla mucho.`],[`Although she studied, she failed the test.`,`Aunque estudió, reprobó el examen.`]],
  err:[`Although it was late, but I called her.`,`Although it was late, I called her.`,`Con although no se usa but en la misma oración.`],
  truco:`Piensa en "aunque". Si ya dijiste aunque, no necesitas decir "pero" otra vez.`,
  prac:'grammar', rel:['even-though','however','instead-of'] },

{ slug:'already', t:'already', tipo:'palabra',
  resp:`Ya. Algo ya pasó o ya está hecho, a veces antes de lo esperado: _I have already eaten._`,
  pron:'ol-RÉ-di',
  uso:[`Se usa sobre todo en oraciones afirmativas. Suele ir entre el auxiliar y el verbo (_have already eaten_) o al final de la frase.`,
       `En preguntas puede mostrar sorpresa (_Is it ten already?_). En negativas no se usa _already_: se usa _yet_.`,
       `Ojo: _all ready_ (dos palabras) significa "todos listos": _We are all ready to go._`],
  ej:[[`I have already eaten.`,`Ya comí.`],[`She already knows the answer.`,`Ella ya sabe la respuesta.`],[`Is it ten o'clock already?`,`¿Ya son las diez?`]],
  err:[`I haven't finished already.`,`I haven't finished yet.`,`En negativas va yet, no already.`],
  truco:`Already = ya está hecho. Yet = todavía no (o "¿ya?" en preguntas).`,
  art:'presente-perfecto', prac:'grammar', rel:['yet','still'] },

{ slug:'get', t:'get', tipo:'palabra',
  resp:`Conseguir, recibir, llegar o ponerse. Es uno de los verbos más usados y cambia según lo que lo acompaña.`,
  pron:'GUÉT',
  uso:[`Mira qué viene después. _Get_ + cosa = conseguir o recibir (_I got a new phone_). _Get_ + lugar = llegar (_We got home late_). _Get_ + adjetivo = ponerse o volverse (_She got angry_).`,
       `También significa "entender" en conversación: _I don't get it._ Y forma muchos phrasal verbs: _get up_ (levantarse), _get on_ (subir), _get off_ (bajar).`,
       `Pasado: _got_. En inglés de Estados Unidos, el participio suele ser _gotten_: _I've gotten better._`],
  ej:[[`I got a message from Leo.`,`Recibí un mensaje de Leo.`],[`What time do you get home?`,`¿A qué hora llegas a casa?`],[`It's getting dark.`,`Está oscureciendo.`],[`I don't get it.`,`No lo entiendo.`]],
  truco:`Fíjate en la palabra que sigue: lugar = llegar, adjetivo = ponerse, cosa = conseguir o recibir.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['look-for','find-out','give-up'] },

{ slug:'would-rather', t:'would rather', tipo:'expresion',
  resp:`Preferiría. Dice lo que preferirías hacer: _I'd rather stay home._`,
  pron:'uud RÁ-der',
  uso:[`Estructura: _would rather_ + verbo en forma base, sin _to_. Se contrae como _I'd rather_. Para negar: _would rather not_ + verbo.`,
       `Para comparar: _would rather A than B_. Y si hablas de lo que quieres que otra persona haga, el verbo siguiente va en pasado: _I'd rather you stayed here._`],
  ej:[[`I'd rather stay home tonight.`,`Preferiría quedarme en casa esta noche.`],[`She'd rather not go.`,`Ella preferiría no ir.`],[`I'd rather walk than take the bus.`,`Prefiero caminar que tomar el bus.`]],
  err:[`I'd rather to stay.`,`I'd rather stay.`,`Después de would rather el verbo va sin to.`],
  truco:`Would rather funciona como can o should: el verbo que sigue va en forma base.`,
  prac:'grammar', rel:['should-have','instead-of','used-to'],
  dialogo:[[`Do you want to go out tonight?`,`¿Quieres salir esta noche?`],[`I'd rather stay home. I'm tired.`,`Preferiría quedarme en casa. Estoy cansado.`],[`Would you rather watch a movie or order pizza?`,`¿Preferirías ver una película o pedir pizza?`],[`I'd rather do both.`,`Preferiría hacer las dos cosas.`]] },

{ slug:'used-to', t:'used to', tipo:'expresion', comun:true,
  resp:`Antes, solía. Habla de algo que pasaba en el pasado y ya no: _I used to live there._`,
  pron:'IÚST tu',
  uso:[`_Used to_ + verbo en forma base habla de hábitos o situaciones del pasado que ya no son así.`,
       `En preguntas y negaciones se escribe _use to_, sin d: _Did you use to...?_, _I didn't use to..._`,
       `No lo confundas con _be used to_ + -ing, que significa "estar acostumbrado": _I'm used to waking up early._`],
  ej:[[`I used to play soccer every weekend.`,`Antes jugaba fútbol todos los fines de semana.`],[`We didn't use to have a car.`,`Antes no teníamos carro.`],[`I'm used to the cold.`,`Estoy acostumbrado al frío.`]],
  err:[`Did you used to live here?`,`Did you use to live here?`,`Con did, used pierde la d: use to.`],
  truco:`Used to = antes sí, ahora no. Be used to = ya me acostumbré.`,
  art:'errores-comunes', prac:'grammar', rel:['would-rather','still'] },

{ slug:'should-have', t:'should have', tipo:'expresion', comun:true,
  resp:`Debería haber, debí. Lamenta o critica algo que no pasó: _I should have called._`,
  pron:'SHÚ-da (rápido)',
  uso:[`Estructura: _should have_ + participio. Habla del pasado y dice qué habría sido mejor hacer. En negativo, _shouldn't have_ + participio: "no debí haberlo hecho".`,
       `Se contrae _should've_. En habla rápida suena como "shuda", y por eso mucha gente lo escribe mal como _should of_. Lo correcto es _should have_.`],
  ej:[[`I should have studied more.`,`Debí estudiar más.`],[`You shouldn't have said that.`,`No debiste decir eso.`],[`We should have left earlier.`,`Deberíamos haber salido antes.`]],
  err:[`I should of called you.`,`I should have called you.`,`Es have (o should've), nunca of.`],
  truco:`Should + have + participio: miras hacia atrás en el tiempo.`,
  prac:'grammar', rel:['would-rather','used-to'],
  dialogo:[[`I missed the bus again.`,`Perdí el bus otra vez.`],[`You should have left earlier.`,`Debiste salir más temprano.`],[`I know. I should have set an alarm.`,`Lo sé. Debí poner una alarma.`],[`Next time, you will.`,`La próxima vez lo harás.`]] },

{ slug:'look-for', t:'look for', tipo:'phrasal',
  resp:`Buscar. Intentas encontrar algo o a alguien: _I'm looking for my keys._`,
  pron:'LUK for',
  uso:[`_Look for_ + lo que buscas. No se separa y no lleva otra preposición.`,
       `Compáralo: _look at_ = mirar, _look for_ = buscar, _find_ = encontrar (ya lo tienes).`],
  ej:[[`I'm looking for my keys.`,`Estoy buscando mis llaves.`],[`She is looking for a new job.`,`Ella está buscando un trabajo nuevo.`],[`What are you looking for?`,`¿Qué estás buscando?`]],
  err:[`I'm looking my keys.`,`I'm looking for my keys.`,`Sin for, look no significa buscar.`],
  truco:`look at = mirar, look for = buscar, find = encontrar.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['find-out','give-up','get'] },

{ slug:'give-up', t:'give up', tipo:'phrasal',
  resp:`Rendirse, o dejar de hacer algo: _Don't give up!_`,
  pron:'GUIV ap',
  uso:[`Puede ir sola (_give up_ = rendirse) o con algo: _give up smoking_ (dejar de fumar). Después de _give up_, el verbo va con -ing.`,
       `Es separable: _give it up_. Con un pronombre, va en medio: _give it up_, no _give up it_.`],
  ej:[[`Don't give up. You're almost there.`,`No te rindas. Ya casi llegas.`],[`He gave up smoking last year.`,`Dejó de fumar el año pasado.`],[`I give up! What's the answer?`,`¡Me rindo! ¿Cuál es la respuesta?`]],
  err:[`He gave up to smoke.`,`He gave up smoking.`,`Después de give up va -ing.`],
  truco:`Give up + -ing: dejar un hábito. Give up solo: rendirse.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['look-for','find-out'] },

{ slug:'find-out', t:'find out', tipo:'phrasal',
  resp:`Averiguar, enterarse. Descubres información que no sabías: _I found out the truth._`,
  pron:'FAIND aut',
  uso:[`_Find out_ habla de información: descubrir un dato. _Find_ habla de encontrar algo concreto, como unas llaves.`,
       `Suele ir seguido de _that, what, who, when, if_: _I need to find out when the store opens._`],
  ej:[[`I need to find out what time it starts.`,`Necesito averiguar a qué hora empieza.`],[`She found out that he was lying.`,`Ella se enteró de que él mentía.`],[`Let me find out and I'll call you back.`,`Déjame averiguar y te llamo.`]],
  err:[`I found out my keys.`,`I found my keys.`,`Para cosas concretas usa find, no find out.`],
  truco:`find = encuentras una cosa. find out = encuentras la información.`,
  art:'phrasal-verbs', prac:'vocabulary', rel:['look-for','give-up'] },

{ slug:'look-forward-to', t:'look forward to', tipo:'expresion',
  resp:`Tener ganas de, esperar con ilusión: _I look forward to meeting you._`,
  pron:'LUK FÓR-uerd tu',
  uso:[`Aquí _to_ es una preposición, así que después va un sustantivo o un verbo con -ing, no el verbo base.`,
       `Es muy común en correos formales: _I look forward to hearing from you._`],
  ej:[[`I'm looking forward to the weekend.`,`Tengo muchas ganas de que llegue el fin de semana.`],[`We look forward to seeing you.`,`Esperamos verte pronto.`],[`She is looking forward to her trip.`,`Ella espera su viaje con ilusión.`]],
  err:[`I look forward to see you.`,`I look forward to seeing you.`,`Después de forward to va -ing.`],
  truco:`Después de look forward to, piensa en -ing.`,
  art:'correo-formal-en-ingles', prac:'grammar', rel:['used-to'] },

{ slug:'however', t:'however', tipo:'palabra',
  resp:`Sin embargo. Une dos ideas con contraste y suena más formal que _but_.`,
  pron:'jau-É-ver',
  uso:[`_However_ suele empezar una oración nueva, con coma después: _It was cheap. However, it was bad._ También puede ir después de punto y coma.`,
       `_But_ va en medio de una oración. _However_ no se pega con una coma entre dos ideas: eso es un error frecuente.`],
  ej:[[`The hotel was nice. However, it was far from the center.`,`El hotel era bonito. Sin embargo, estaba lejos del centro.`],[`I wanted to go; however, I had to work.`,`Quería ir; sin embargo, tenía que trabajar.`]],
  err:[`It was cheap, however it was bad.`,`It was cheap. However, it was bad.`,`Antes de however va punto o punto y coma, no solo coma.`],
  truco:`However = otra oración que contradice la anterior.`,
  art:'correo-formal-en-ingles', prac:'vocabulary', rel:['although','even-though'] },

{ slug:'actually', t:'actually', tipo:'palabra', comun:true,
  resp:`En realidad, de hecho. No significa "actualmente".`,
  pron:'ÁK-chua-li',
  uso:[`_Actually_ sirve para corregir algo o dar un dato que sorprende. Se parece a "actualmente", pero es un falso amigo.`,
       `"Actualmente" en inglés es _currently_ o _at the moment_.`],
  ej:[[`Actually, I'm from Colombia, not Mexico.`,`En realidad, soy de Colombia, no de México.`],[`I actually liked the movie.`,`De hecho, me gustó la película.`],[`I'm currently studying English.`,`Actualmente estudio inglés.`]],
  err:[`Actually I work in Madrid. (quería decir "actualmente")`,`Currently I work in Madrid.`,`Actually = en realidad; currently = ahora.`],
  truco:`actually = en realidad. currently = ahora.`,
  prac:'vocabulary', rel:[] },

{ slug:'even-though', t:'even though', tipo:'expresion',
  resp:`Aunque, a pesar de que. Es una versión más fuerte de _although_ para hechos reales.`,
  pron:'Í-ven DÓU',
  uso:[`_Even though_ + oración completa. Habla de algo que sí es real y que contrasta con lo otro.`,
       `_Even if_ es distinto: habla de algo que podría pasar. _Even if it rains, we'll go._`],
  ej:[[`Even though he was tired, he kept working.`,`Aunque estaba cansado, siguió trabajando.`],[`I went to work even though I was sick.`,`Fui a trabajar aunque estaba enfermo.`],[`Even if it rains, we'll go.`,`Aunque llueva, iremos.`]],
  err:[`Even though of the traffic, I arrived on time.`,`Even though there was traffic, I arrived on time.`,`Después de even though va sujeto + verbo.`],
  truco:`even though = ya pasó o es real. even if = tal vez pase.`,
  prac:'grammar', rel:['although','however'] },

{ slug:'instead-of', t:'instead of', tipo:'expresion',
  resp:`En lugar de, en vez de. Dice lo que eliges o haces en vez de otra cosa.`,
  pron:'in-STÉD ov',
  uso:[`_Instead of_ + sustantivo o verbo con -ing. _Instead_ sola cierra la frase o va al inicio: _I didn't call. I wrote instead._`],
  ej:[[`Let's walk instead of taking the bus.`,`Caminemos en vez de tomar el bus.`],[`I'll have water instead of soda.`,`Tomaré agua en lugar de refresco.`],[`I didn't call her. I wrote to her instead.`,`No la llamé. Le escribí en su lugar.`]],
  err:[`Let's walk instead to take the bus.`,`Let's walk instead of taking the bus.`,`Después de instead of va -ing.`],
  truco:`Instead of + -ing. Instead sola = "en cambio".`,
  prac:'grammar', rel:['would-rather','although'] },

{ slug:'yet', t:'yet', tipo:'palabra',
  resp:`Todavía (no) o ya (en preguntas). Se usa en negativas y preguntas, casi siempre al final.`,
  pron:'IÉT',
  uso:[`Negativa: _I haven't finished yet_ (todavía no terminé). Pregunta: _Have you finished yet?_ (¿ya terminaste?).`,
       `En afirmativas no se usa _yet_ con este sentido: ahí va _already_.`],
  ej:[[`I haven't seen that movie yet.`,`Todavía no he visto esa película.`],[`Has she called yet?`,`¿Ya llamó?`],[`Not yet.`,`Todavía no.`]],
  err:[`I have finished yet.`,`I have already finished.`,`En afirmativas se usa already, no yet.`],
  truco:`yet = esperas que pase. already = ya pasó.`,
  art:'presente-perfecto', prac:'grammar', rel:['already','still'] },

{ slug:'still', t:'still', tipo:'palabra',
  resp:`Todavía, aún. Algo sigue igual y no ha cambiado.`,
  pron:'STIL',
  uso:[`_Still_ va antes del verbo principal, pero después de _to be_: _I still live here_, _She is still here_.`,
       `En negativas va antes del auxiliar: _I still haven't called._ No lo confundas con _yet_: _still_ = sigue pasando; _yet_ = esperas que pase.`],
  ej:[[`I still love pizza.`,`Todavía me encanta la pizza.`],[`Are you still working?`,`¿Sigues trabajando?`],[`He still doesn't know.`,`Él todavía no sabe.`]],
  err:[`I live still here.`,`I still live here.`,`Still va antes del verbo, no al final.`],
  truco:`still = sigue igual.`,
  prac:'grammar', rel:['already','yet'] },

{ slug:'enough', t:'enough', tipo:'palabra',
  resp:`Suficiente, bastante. Cambia de lugar: antes de un sustantivo, después de un adjetivo.`,
  pron:'i-NÁF',
  uso:[`Con sustantivos va antes: _enough money_. Con adjetivos y adverbios va después: _tall enough_.`,
       `Puede seguir _to_ + verbo: _old enough to drive_.`],
  ej:[[`We have enough time.`,`Tenemos suficiente tiempo.`],[`She isn't old enough to drive.`,`Ella no tiene edad suficiente para manejar.`],[`Is it big enough?`,`¿Es lo bastante grande?`]],
  err:[`She is enough tall.`,`She is tall enough.`,`Con adjetivos, enough va después.`],
  truco:`Cosas: enough antes. Cualidades: enough después.`,
  prac:'grammar', rel:[] },

/* ---------------- DIFERENCIAS ---------------- */
{ slug:'since-vs-for', t:'since vs for', tipo:'diferencia',
  resp:`Since = desde (el momento en que empezó). For = durante (cuánto tiempo).`,
  pron:'SINS / FOR',
  uso:[`_Since_ + un punto en el tiempo: _since 2020_, _since Monday_, _since I was a child_. _For_ + una duración: _for two years_, _for three hours_.`,
       `Los dos suelen ir con presente perfecto: _I have lived here since 2020_ es lo mismo que _I have lived here for five years_.`],
  ej:[[`I have lived here since 2020.`,`Vivo aquí desde 2020.`],[`I have lived here for five years.`,`Vivo aquí desde hace cinco años.`],[`She has worked here since June.`,`Ella trabaja aquí desde junio.`]],
  err:[`I have lived here since five years.`,`I have lived here for five years.`,`Una cantidad de tiempo va con for.`],
  truco:`¿Puedes contarlo (dos años, tres horas)? For. ¿Es una fecha o un momento? Since.`,
  art:'presente-perfecto', prac:'grammar', rel:['already','yet'] },

{ slug:'make-vs-do', t:'make vs do', tipo:'diferencia', comun:true,
  resp:`Make = crear o producir algo. Do = hacer una tarea, acción o actividad.`,
  pron:'MEIK / DU',
  uso:[`_Make_ crea algo que antes no existía: _make a cake_, _make a plan_, _make a mistake_, _make money_, _make a decision_.`,
       `_Do_ habla de tareas y actividades: _do homework_, _do the dishes_, _do your best_, _do a favor_. Muchas combinaciones son fijas: conviene aprenderlas juntas.`],
  ej:[[`I made breakfast for everyone.`,`Preparé el desayuno para todos.`],[`I did my homework after dinner.`,`Hice mi tarea después de cenar.`],[`She made a mistake.`,`Ella cometió un error.`],[`Can you do me a favor?`,`¿Me haces un favor?`]],
  err:[`I did a mistake.`,`I made a mistake.`,`Mistake va con make.`],
  truco:`Make = el resultado es algo nuevo. Do = una tarea que se hace.`,
  art:'errores-comunes', prac:'vocabulary', rel:['say-vs-tell','hear-vs-listen'] },

{ slug:'hear-vs-listen', t:'hear vs listen', tipo:'diferencia',
  resp:`Hear = oír, sin querer. Listen = escuchar con atención y a propósito.`,
  pron:'JIR / LÍ-sen',
  uso:[`_Hear_ no lleva preposición: _I hear music_. _Listen_ va con _to_: _I listen to music_. En _listen_ la t no se pronuncia.`,
       `_Hear_ pasa solo; _listen_ es algo que decides hacer.`],
  ej:[[`I can hear the neighbors.`,`Oigo a los vecinos.`],[`Please listen to me.`,`Por favor, escúchame.`],[`I heard a noise outside.`,`Oí un ruido afuera.`]],
  err:[`I listen music every day.`,`I listen to music every day.`,`Listen siempre lleva to.`],
  truco:`listen to: siempre con to. hear: sin to.`,
  prac:'listening', rel:['make-vs-do'] },

{ slug:'person-vs-people', t:'person vs people', tipo:'diferencia', comun:true,
  resp:`Person = una persona. People = varias personas, y ya es plural.`,
  pron:'PÉR-sen / PÍ-pol',
  uso:[`_People_ es el plural normal de _person_ y lleva verbo en plural: _People are..._ _Persons_ existe, pero solo en textos legales; en la vida diaria se usa _people_.`,
       `_Peoples_ (con s) significa "pueblos" o "naciones".`],
  ej:[[`She is a nice person.`,`Ella es una buena persona.`],[`Many people speak English.`,`Mucha gente habla inglés.`],[`Three people are waiting outside.`,`Tres personas esperan afuera.`]],
  err:[`The people is here.`,`The people are here.`,`People es plural: va con are.`],
  truco:`people ya es plural: no le agregues -s.`,
  prac:'grammar', rel:['much-vs-many'] },

{ slug:'was-vs-were', t:'was vs were', tipo:'diferencia', comun:true,
  resp:`Was = fui, era, estaba (I, he, she, it). Were = fuiste, fueron, estaban (you, we, they).`,
  pron:'UAS / UER',
  uso:[`Son el pasado de _to be_. _Was_ va con _I, he, she, it_. _Were_ va con _you, we, they_. Con _you_ siempre es _were_, aunque hables con una sola persona.`,
       `Negativo: _wasn't_ y _weren't_. Pregunta: _Was he...?_ _Were they...?_ En frases como _If I were you_, se usa _were_ incluso con _I_.`],
  ej:[[`I was at home yesterday.`,`Ayer estuve en casa.`],[`They were very tired.`,`Ellos estaban muy cansados.`],[`Were you at the party?`,`¿Estuviste en la fiesta?`]],
  err:[`You was late.`,`You were late.`,`You siempre lleva were.`],
  truco:`Was solo con I, he, she, it. Todo lo demás: were.`,
  art:'verbo-to-be', art2:'pasado-simple', prac:'grammar', rel:['much-vs-many'] },

{ slug:'much-vs-many', t:'much vs many', tipo:'diferencia',
  resp:`Many = con cosas que se cuentan (plural). Much = con cosas que no se cuentan.`,
  pron:'MACH / MÉ-ni',
  uso:[`_Many_ + sustantivo contable en plural: _many friends_. _Much_ + sustantivo incontable: _much water_, _much time_.`,
       `Se usan sobre todo en preguntas y negativas. En afirmativas suena más natural _a lot of_: _I have a lot of friends._`],
  ej:[[`How many people are coming?`,`¿Cuántas personas vienen?`],[`I don't have much time.`,`No tengo mucho tiempo.`],[`There aren't many chairs.`,`No hay muchas sillas.`]],
  err:[`How much people are there?`,`How many people are there?`,`People se cuenta: many.`],
  truco:`¿Puedes contarlos uno por uno? Many. ¿Es una masa, como agua o tiempo? Much.`,
  prac:'grammar', rel:['fewer-vs-less','person-vs-people'] },

{ slug:'a-vs-an', t:'a vs an', tipo:'diferencia',
  resp:`An va antes de un sonido de vocal. A va antes de un sonido de consonante.`,
  pron:'a (corto) / AN',
  uso:[`Importa el sonido, no la letra. _An hour_ (la h no suena) y _a university_ (suena "iu", como consonante).`,
       `Para decidir, di la palabra en voz alta y escucha cómo empieza.`],
  ej:[[`She is an engineer.`,`Ella es ingeniera.`],[`I need an umbrella.`,`Necesito un paraguas.`],[`He goes to a university in Texas.`,`Él va a una universidad en Texas.`],[`We waited for an hour.`,`Esperamos una hora.`]],
  err:[`I have an university degree.`,`I have a university degree.`,`University empieza con sonido "iu": a.`],
  truco:`Escucha la primera palabra: ¿suena a vocal? An. ¿A consonante? A.`,
  prac:'grammar', rel:[] },

{ slug:'say-vs-tell', t:'say vs tell', tipo:'diferencia',
  resp:`Say = decir las palabras. Tell = decirle algo a alguien (lleva la persona).`,
  pron:'SEI / TEL',
  uso:[`_Tell_ va con la persona: _tell me_, _tell her_. _Say_ va con lo que se dice: _say hello_. Si quieres nombrar a la persona con _say_, necesitas _to_: _say to me_.`,
       `Combinaciones fijas: _tell the truth_, _tell a lie_, _tell a story_; _say goodbye_, _say sorry_.`],
  ej:[[`She said she was tired.`,`Ella dijo que estaba cansada.`],[`She told me she was tired.`,`Ella me dijo que estaba cansada.`],[`Tell me the truth.`,`Dime la verdad.`]],
  err:[`He said me a secret.`,`He told me a secret.`,`Con una persona directa, usa tell.`],
  truco:`tell + persona. say + palabras.`,
  prac:'grammar', rel:['make-vs-do','hear-vs-listen'] },

{ slug:'borrow-vs-lend', t:'borrow vs lend', tipo:'diferencia',
  resp:`Borrow = pedir prestado (tú recibes). Lend = prestar (tú das).`,
  pron:'BÓ-rou / LEND',
  uso:[`Si recibes algo por un tiempo: _borrow_. Si lo das por un tiempo: _lend_. El pasado de _lend_ es _lent_.`,
       `_Can I borrow your pen?_ y _Can you lend me your pen?_ piden lo mismo desde lados distintos.`],
  ej:[[`Can I borrow your charger?`,`¿Me prestas tu cargador?`],[`Could you lend me ten dollars?`,`¿Podrías prestarme diez dólares?`],[`I lent her my book.`,`Le presté mi libro.`]],
  err:[`Can you borrow me your pen?`,`Can you lend me your pen?`,`Quien da el objeto lo presta: lend.`],
  truco:`borrow = lo recibo. lend = lo doy.`,
  prac:'grammar', rel:['bring-vs-take'] },

{ slug:'bring-vs-take', t:'bring vs take', tipo:'diferencia',
  resp:`Bring = traer (hacia donde está quien habla). Take = llevar (hacia otro lugar).`,
  pron:'BRING / TEIK',
  uso:[`_Bring_ va hacia el lugar donde estás tú o donde estará quien escucha. _Take_ va hacia otro lugar, lejos de ti.`,
       `Pasados: _brought_ y _took_.`],
  ej:[[`Please bring your passport tomorrow.`,`Por favor, trae tu pasaporte mañana.`],[`I take my son to school every day.`,`Llevo a mi hijo a la escuela todos los días.`],[`Can you bring me a glass of water?`,`¿Me traes un vaso de agua?`]],
  err:[`Take me a glass of water, please.`,`Bring me a glass of water, please.`,`Hacia mí: bring.`],
  truco:`bring = hacia aquí. take = hacia allá.`,
  prac:'grammar', rel:['borrow-vs-lend'] },

{ slug:'affect-vs-effect', t:'affect vs effect', tipo:'diferencia', comun:true,
  resp:`Affect = verbo (afectar). Effect = sustantivo (efecto).`,
  pron:'a-FÉKT / i-FÉKT',
  uso:[`La mayoría de las veces, _affect_ es la acción y _effect_ es el resultado: _The weather affects my mood_ y _The weather has an effect on my mood_.`,
       `Hay usos raros al revés, pero no hacen falta para hablar o escribir en el día a día.`],
  ej:[[`The rain affected our plans.`,`La lluvia afectó nuestros planes.`],[`The medicine had a good effect.`,`La medicina tuvo un buen efecto.`],[`Stress can affect your sleep.`,`El estrés puede afectar tu sueño.`]],
  err:[`The rain effected my plans.`,`The rain affected my plans.`,`Como verbo, normalmente es affect.`],
  truco:`affect = acción. effect = efecto (el resultado).`,
  prac:'vocabulary', rel:[] },

{ slug:'fewer-vs-less', t:'fewer vs less', tipo:'diferencia',
  resp:`Fewer = menos (cosas que se cuentan). Less = menos (cosas que no se cuentan).`,
  pron:'FIÚ-er / LES',
  uso:[`_Fewer cars_ (los carros se cuentan), _less traffic_ (el tráfico no se cuenta).`,
       `En la conversación mucha gente dice _less_ para todo, pero en exámenes y textos formales se espera _fewer_ con cosas que se cuentan.`],
  ej:[[`I have fewer problems now.`,`Ahora tengo menos problemas.`],[`Drink less coffee.`,`Toma menos café.`],[`There are fewer people today.`,`Hay menos gente hoy.`]],
  err:[`There are less people today.`,`There are fewer people today.`,`People se cuenta: fewer (en formal).`],
  truco:`fewer = cuento. less = no cuento.`,
  prac:'grammar', rel:['much-vs-many'] },

{ slug:'its-vs-it-s', t:`its vs it's`, tipo:'diferencia', comun:true,
  resp:`It's = it is o it has. Its = de él, de ella, de eso (posesivo).`,
  pron:'ITS / ITS (suenan igual)',
  uso:[`_It's_ lleva apóstrofe porque es una contracción: _it is_ o _it has_. _Its_, sin apóstrofe, indica que algo le pertenece: _The dog wagged its tail._`,
       `Prueba rápida: cambia la palabra por _it is_. Si la frase sigue teniendo sentido, escribe _it's_.`],
  ej:[[`It's a beautiful day.`,`Es un día hermoso.`],[`The cat licked its paw.`,`El gato se lamió la pata.`],[`It's been a long week.`,`Ha sido una semana larga.`]],
  err:[`The company changed it's name.`,`The company changed its name.`,`Aquí es posesivo: its, sin apóstrofe.`],
  truco:`Cámbialo por "it is". ¿Funciona? Es it's.`,
  prac:'grammar', rel:['their-there-theyre','your-vs-youre'] },

{ slug:'then-vs-than', t:'then vs than', tipo:'diferencia', comun:true,
  resp:`Then = entonces, luego (tiempo). Than = que (para comparar).`,
  pron:'DEN / DAN',
  uso:[`_Then_ habla de orden o de consecuencia: _First we ate, then we left._ _Than_ aparece después de un comparativo: _taller than_, _more than_.`],
  ej:[[`She is taller than me.`,`Ella es más alta que yo.`],[`Finish your homework, then you can play.`,`Termina tu tarea, luego puedes jugar.`],[`If you're tired, then rest.`,`Si estás cansado, entonces descansa.`]],
  err:[`She is older then me.`,`She is older than me.`,`Para comparar se usa than.`],
  truco:`then = tiempo. than = comparación.`,
  prac:'grammar', rel:['its-vs-it-s'] },

{ slug:'their-there-theyre', t:`their / there / they're`, tipo:'diferencia', comun:true,
  resp:`Their = de ellos. There = allí o hay. They're = they are.`,
  pron:'DER (las tres suenan casi igual)',
  uso:[`_Their_ indica posesión: _their house_. _There_ indica lugar o existencia: _over there_, _there is a problem_. _They're_ es la contracción de _they are_.`,
       `Prueba: cambia por _they are_. Si funciona, es _they're_.`],
  ej:[[`Their house is big.`,`Su casa es grande.`],[`Put it over there.`,`Ponlo allá.`],[`They're my friends.`,`Ellos son mis amigos.`]],
  err:[`Their going home.`,`They're going home.`,`Aquí es they are: they're.`],
  truco:`their = de ellos. there = lugar. they're = they are.`,
  prac:'grammar', rel:['its-vs-it-s','your-vs-youre'] },

{ slug:'your-vs-youre', t:`your vs you're`, tipo:'diferencia', comun:true,
  resp:`Your = tu, tus. You're = you are (tú eres, tú estás).`,
  pron:'YOR / YOR (suenan casi igual)',
  uso:[`_Your_ va antes de un sustantivo: _your phone_. _You're_ es una contracción: _you are_.`,
       `El error más famoso: _Your welcome_. Lo correcto es _You're welcome_ ("de nada").`],
  ej:[[`Your phone is ringing.`,`Tu teléfono está sonando.`],[`You're late.`,`Llegas tarde.`],[`You're welcome.`,`De nada.`]],
  err:[`Your welcome.`,`You're welcome.`,`Es you are welcome: you're.`],
  truco:`Cámbialo por "you are". ¿Funciona? Es you're.`,
  prac:'grammar', rel:['its-vs-it-s','their-there-theyre'] },

{ slug:'lose-vs-loose', t:'lose vs loose', tipo:'diferencia', comun:true,
  resp:`Lose = perder (verbo). Loose = suelto, flojo (adjetivo).`,
  pron:'LUUZ / LUUS',
  uso:[`_Lose_ es un verbo: _lose a game_, _lose your keys_. Su pasado es _lost_. _Loose_ describe algo que no está apretado: _a loose shirt_.`,
       `Cuidado con la pronunciación: _lose_ termina en sonido "z" y _loose_ en sonido "s".`],
  ej:[[`I don't want to lose my job.`,`No quiero perder mi trabajo.`],[`This shirt is too loose.`,`Esta camisa está muy suelta.`],[`We lost the game.`,`Perdimos el partido.`]],
  err:[`I don't want to loose my keys.`,`I don't want to lose my keys.`,`El verbo perder es lose.`],
  truco:`lose pierde una o. loose tiene una o de más: suelto, con espacio.`,
  prac:'vocabulary', rel:[] },

{ slug:'good-vs-well', t:'good vs well', tipo:'diferencia', comun:true,
  resp:`Good = bueno (adjetivo). Well = bien (adverbio, cómo haces algo).`,
  pron:'GUD / UEL',
  uso:[`_Good_ describe personas o cosas: _a good teacher_. _Well_ describe cómo se hace algo: _She sings well._`,
       `_Well_ también puede significar "sano": _I don't feel well._`],
  ej:[[`He is a good player.`,`Él es un buen jugador.`],[`He plays well.`,`Él juega bien.`],[`I'm not feeling well.`,`No me siento bien (de salud).`]],
  err:[`She sings very good.`,`She sings very well.`,`Para decir cómo canta, usa well.`],
  truco:`good = nombre (a good friend). well = acción (works well).`,
  prac:'grammar', rel:[] },

{ slug:'as-vs-like', t:'as vs like', tipo:'diferencia',
  resp:`Like = como, parecido a. As = como, en el papel o función de.`,
  pron:'AS / LAIK',
  uso:[`_Like_ compara cosas parecidas: _She sings like a pro_ (canta como una profesional, aunque no lo es). _As_ dice qué función cumple algo o alguien: _She works as a teacher_ (es profesora).`],
  ej:[[`He runs like the wind.`,`Corre como el viento.`],[`I work as a nurse.`,`Trabajo como enfermera.`],[`Do it as I showed you.`,`Hazlo como te mostré.`]],
  err:[`I work like a waiter. (y sí eres mesero)`,`I work as a waiter.`,`Si es tu trabajo real, usa as.`],
  truco:`as = lo que es. like = parecido a.`,
  prac:'grammar', rel:[] },

/* ---------------- PRONUNCIACION Y USO FRECUENTE: TANDA 1 ---------------- */
{ slug:'mustnt', t:`mustn't`, tipo:'gramatica', comun:true,
  resp:`No debes, no está permitido. Es la contracción de _must not_.`, pron:'MÁS-nt',
  uso:[`_Mustn't_ expresa una prohibición fuerte. Va seguido de un verbo en forma base: _You mustn't park here._ No significa "no tienes que"; para eso usa _don't have to_.`],
  ej:[[`You mustn't use your phone in class.`,`No debes usar el teléfono en clase.`],[`You mustn't tell anyone.`,`No debes decírselo a nadie.`]],
  err:[`You mustn't to smoke here.`,`You mustn't smoke here.`,`Después de mustn't va el verbo sin to.`], truco:`Mustn't = está prohibido. Don't have to = no es necesario.`, prac:'grammar', rel:['shouldnt','cant','wont'] },
{ slug:'shouldnt', t:`shouldn't`, tipo:'gramatica', comun:true,
  resp:`No deberías. Da un consejo negativo: _You shouldn't worry._`, pron:'SHÚ-dnt',
  uso:[`Es la contracción de _should not_. Se usa para recomendar no hacer algo, no para prohibirlo con fuerza.`],
  ej:[[`You shouldn't skip breakfast.`,`No deberías saltarte el desayuno.`],[`She shouldn't drive when she's tired.`,`Ella no debería conducir cuando está cansada.`]],
  err:[`You shouldn't to go.`,`You shouldn't go.`,`Después de shouldn't va el verbo base.`], prac:'grammar', rel:['mustnt','should','couldnt'] },
{ slug:'wouldnt', t:`wouldn't`, tipo:'gramatica', comun:true,
  resp:`No haría, no gustaría o no quería, según el contexto. Es _would not_.`, pron:'WÚ-dnt',
  uso:[`Se usa en condicionales, preferencias y situaciones hipotéticas: _I wouldn't do that_. El apóstrofe reemplaza la o de _not_.`],
  ej:[[`I wouldn't buy it without checking first.`,`No lo compraría sin revisar primero.`],[`He wouldn't answer my question.`,`Él no quiso responder mi pregunta.`]],
  prac:'grammar', rel:['would','couldnt','shouldnt'] },
{ slug:'couldnt', t:`couldn't`, tipo:'gramatica', comun:true,
  resp:`No podía o no pude. Es la forma negativa de _could_.`, pron:'KUD-nt',
  uso:[`Habla de falta de capacidad, posibilidad o permiso en el pasado: _I couldn't sleep_. También sirve para sugerencias: _You couldn't ask her._`],
  ej:[[`I couldn't find my keys.`,`No pude encontrar mis llaves.`],[`We couldn't hear the teacher.`,`No podíamos oír a la profesora.`]],
  err:[`I couldn't to understand.`,`I couldn't understand.`,`Couldn't va con verbo base.`], prac:'grammar', rel:['could','wouldnt','shouldnt'] },
{ slug:'werent', t:`weren't`, tipo:'gramatica', comun:true,
  resp:`No eran o no estaban. Es la contracción de _were not_.`, pron:'UÉR-nt',
  uso:[`Se usa con you, we y they en pasado: _They weren't ready_. También aparece en el condicional irreal: _If I weren't busy..._`],
  ej:[[`They weren't at home.`,`Ellos no estaban en casa.`],[`We weren't late.`,`No llegamos tarde.`]], prac:'grammar', rel:['wasnt','were','was-vs-were'] },
{ slug:'wasnt', t:`wasn't`, tipo:'gramatica', comun:true,
  resp:`No era o no estaba. Es la contracción de _was not_.`, pron:'UÓ-znt',
  uso:[`Va con I, he, she e it en pasado. Para you, we y they se usa _weren't_.`],
  ej:[[`I wasn't hungry.`,`No tenía hambre.`],[`The movie wasn't long.`,`La película no fue larga.`]], prac:'grammar', rel:['werent','was-vs-were','were'] },
{ slug:'doesnt', t:`doesn't`, tipo:'gramatica', comun:true,
  resp:`No hace o no es. Es _does not_ con he, she o it en presente.`, pron:'DÁ-znt',
  uso:[`Después de _doesn't_, el verbo vuelve a la forma base: _She doesn't work_, no _doesn't works_.`],
  ej:[[`She doesn't speak French.`,`Ella no habla francés.`],[`It doesn't matter.`,`No importa.`]],
  err:[`He doesn't likes coffee.`,`He doesn't like coffee.`,`Does ya lleva la marca de tercera persona.`], prac:'grammar', rel:['didnt','isnt','arent'] },
{ slug:'didnt', t:`didn't`, tipo:'gramatica', comun:true,
  resp:`No hice, no hizo o no hicieron. Es la contracción de _did not_.`, pron:'DÍ-dnt',
  uso:[`Niega acciones pasadas con cualquier sujeto. El verbo que sigue siempre va en forma base: _didn't go_, no _didn't went_.`],
  ej:[[`I didn't call him yesterday.`,`No lo llamé ayer.`],[`They didn't understand the question.`,`Ellos no entendieron la pregunta.`]],
  err:[`She didn't went.`,`She didn't go.`,`Con did, usa el verbo base.`], prac:'grammar', rel:['doesnt','wasnt','was-vs-were'] },
{ slug:'isnt', t:`isn't`, tipo:'gramatica', comun:true,
  resp:`No es o no está. Es la contracción de _is not_.`, pron:'Í-znt',
  uso:[`Se usa con he, she, it y nombres en singular. Puede negar una característica o una situación: _It isn't expensive_.`],
  ej:[[`This isn't my bag.`,`Esta no es mi bolsa.`],[`He isn't ready yet.`,`Él todavía no está listo.`]], prac:'grammar', rel:['arent','doesnt','wasnt'] },
{ slug:'arent', t:`aren't`, tipo:'gramatica', comun:true,
  resp:`No son o no están. Es la contracción de _are not_.`, pron:'AR-nt',
  uso:[`Va con you, we y they. En preguntas negativas es frecuente: _Aren't you coming?_`],
  ej:[[`We aren't busy today.`,`No estamos ocupados hoy.`],[`They aren't from Spain.`,`Ellos no son de España.`]], prac:'grammar', rel:['isnt','werent','youre'] },
{ slug:'havent', t:`haven't`, tipo:'gramatica', comun:true,
  resp:`No he, no has, no hemos o no han. Es _have not_.`, pron:'JÁ-vent',
  uso:[`Se usa sobre todo en presente perfecto con I, you, we y they: _I haven't finished_.`],
  ej:[[`I haven't seen that show.`,`No he visto esa serie.`],[`They haven't arrived yet.`,`Ellos todavía no han llegado.`]], prac:'grammar', rel:['hasnt','hadnt','yet'] },
{ slug:'hasnt', t:`hasn't`, tipo:'gramatica', comun:true,
  resp:`No ha. Es la contracción de _has not_.`, pron:'JÁ-znt',
  uso:[`Va con he, she e it en presente perfecto: _She hasn't called_.`],
  ej:[[`He hasn't finished his homework.`,`Él no ha terminado su tarea.`],[`The bus hasn't arrived.`,`El bus no ha llegado.`]], prac:'grammar', rel:['havent','hadnt','yet'] },
{ slug:'hadnt', t:`hadn't`, tipo:'gramatica', comun:true,
  resp:`No había. Es la contracción de _had not_.`, pron:'JÁ-dnt',
  uso:[`Se usa con todos los sujetos en pasado perfecto para una acción anterior a otra acción pasada.`],
  ej:[[`I hadn't eaten before the meeting.`,`No había comido antes de la reunión.`],[`She hadn't met him before.`,`Ella no lo había conocido antes.`]], prac:'grammar', rel:['havent','hasnt','didnt'] },
{ slug:'wont', t:`won't`, tipo:'gramatica', comun:true,
  resp:`No haré, no será o no ocurrirá. Es la forma negativa irregular de _will_.`, pron:'UÓUNT',
  uso:[`No se escribe _willn't_. Usa _won't_ para negar el futuro: _It won't rain tomorrow_.`],
  ej:[[`I won't be late again.`,`No volveré a llegar tarde.`],[`This won't take long.`,`Esto no tardará mucho.`]],
  err:[`I willn't call.`,`I won't call.`,`La contracción correcta de will not es won't.`], prac:'grammar', rel:['would','mustnt','cant'] },
{ slug:'cant', t:`can't`, tipo:'gramatica', comun:true,
  resp:`No puedo o no puede. Es la contracción de _cannot_.`, pron:'KÁNT',
  uso:[`Expresa falta de capacidad, permiso o posibilidad. En inglés estadounidense, el sonido final de _can't_ suele ser más marcado que en _can_.`],
  ej:[[`I can't open this jar.`,`No puedo abrir este frasco.`],[`You can't park here.`,`No puedes estacionar aquí.`]], prac:'grammar', rel:['couldnt','mustnt','wont'] },
{ slug:'ive', t:`I've`, tipo:'gramatica', comun:true,
  resp:`He, he estado o tengo. Es la contracción de _I have_.`, pron:'ÁIV',
  uso:[`Con participio forma presente perfecto: _I've finished_. Con un sustantivo puede expresar posesión: _I've got a question_.`],
  ej:[[`I've lived here for years.`,`He vivido aquí durante años.`],[`I've got your message.`,`Tengo tu mensaje.`]], prac:'grammar', rel:['havent','id-contraction','ill-contraction'] },
{ slug:'id-contraction', t:`I'd`, tipo:'gramatica', comun:true,
  resp:`Yo haría, me gustaría o yo había. Puede significar _I would_ o _I had_.`, pron:'ÁID',
  uso:[`El contexto lo aclara: _I'd like coffee_ = I would like; _I'd already left_ = I had already left.`],
  ej:[[`I'd like a glass of water.`,`Me gustaría un vaso de agua.`],[`I'd never seen snow before.`,`Nunca había visto nieve antes.`]], prac:'grammar', rel:['ive','ill-contraction','would'] },
{ slug:'ill-contraction', t:`I'll`, tipo:'gramatica', comun:true,
  resp:`Yo haré o voy a. Es la contracción de _I will_.`, pron:'ÁIL',
  uso:[`Se usa para decisiones, promesas y predicciones sobre el futuro: _I'll call you later_.`],
  ej:[[`I'll send it tonight.`,`Lo enviaré esta noche.`],[`I'll help you with that.`,`Te ayudaré con eso.`]], prac:'grammar', rel:['ive','id-contraction','wont'] },
{ slug:'youre', t:`you're`, tipo:'gramatica', comun:true,
  resp:`Tú eres o tú estás. Es la contracción de _you are_.`, pron:'YUR',
  uso:[`No lo confundas con _your_, que indica posesión. Prueba cambiarlo por _you are_: si funciona, escribe _you're_.`],
  ej:[[`You're doing great.`,`Lo estás haciendo muy bien.`],[`You're my best friend.`,`Eres mi mejor amigo.`]], prac:'grammar', rel:['your-vs-youre','theyre','were'] },
{ slug:'theyre', t:`they're`, tipo:'gramatica', comun:true,
  resp:`Ellos son o están. Es la contracción de _they are_.`, pron:'DER',
  uso:[`Siempre puede expandirse a _they are_. No lo confundas con _their_ (de ellos) ni _there_ (allí o hay).`],
  ej:[[`They're waiting outside.`,`Ellos están esperando afuera.`],[`They're very kind.`,`Ellos son muy amables.`]], prac:'grammar', rel:['their-there-theyre','youre','were'] },
{ slug:'were-contraction', t:`we're (we are)`, tipo:'gramatica', comun:true,
  resp:`Nosotros somos o estamos. Es la contracción de _we are_.`, pron:'UÍR',
  uso:[`Se usa en presente con we: _We're ready_. El apóstrofe no aparece en _were_, que es pasado.`],
  ej:[[`We're going home now.`,`Nos vamos a casa ahora.`],[`We're happy to help.`,`Estamos felices de ayudar.`]], prac:'grammar', rel:['youre','theyre','were'] },

{ slug:'though', t:'though', tipo:'palabra',
  resp:`Aunque. También puede ir al final y significar "eso sí" o "aunque" en conversación.`, pron:'DÓU',
  uso:[`_Though_ conecta ideas con contraste. Al final de una frase es informal: _It was expensive. I liked it, though._`],
  ej:[[`Though it was late, we kept talking.`,`Aunque era tarde, seguimos hablando.`],[`I don't know him well, though.`,`No lo conozco bien, eso sí.`]], prac:'grammar', rel:['although','even-though','thought'] },
{ slug:'thought', t:'thought', tipo:'palabra',
  resp:`Pensé o pensamiento. Es el pasado de _think_ y tiene un sonido TH sordo.`, pron:'ZÓT',
  uso:[`Como verbo, es el pasado de _think_: _I thought_. Como sustantivo, es una idea: _a thought_.`],
  ej:[[`I thought you were at work.`,`Pensé que estabas en el trabajo.`],[`That thought made me smile.`,`Ese pensamiento me hizo sonreír.`]], prac:'grammar', rel:['think','though','through'] },
{ slug:'through', t:'through', tipo:'palabra',
  resp:`A través de, por medio de o hasta el final.`, pron:'ZRUU',
  uso:[`Indica movimiento de un lado al otro: _walk through the park_. También significa terminar algo: _read through the report_.`],
  ej:[[`We walked through the tunnel.`,`Caminamos por el túnel.`],[`I read through the email.`,`Leí el correo completo.`]], prac:'vocabulary', rel:['though','thought','throughout'] },
{ slug:'throughout', t:'throughout', tipo:'palabra',
  resp:`Por todo o durante todo.`, pron:'zruu-ÁUT',
  uso:[`Se usa para todo un lugar o todo un periodo: _throughout the city_, _throughout the year_.`],
  ej:[[`It rained throughout the day.`,`Llovió durante todo el día.`],[`The same rule applies throughout the book.`,`La misma regla se aplica en todo el libro.`]], prac:'vocabulary', rel:['through','though','without'] },
{ slug:'tough', t:'tough', tipo:'palabra',
  resp:`Difícil, duro o resistente. Rima con _rough_, no con _though_.`, pron:'TÁF',
  uso:[`Describe una situación difícil o una persona fuerte: _a tough decision_, _a tough person_.`],
  ej:[[`This exam is tough.`,`Este examen es difícil.`],[`It was a tough week.`,`Fue una semana dura.`]], prac:'vocabulary', rel:['rough','enough','though'] },
{ slug:'rough', t:'rough', tipo:'palabra',
  resp:`Áspero, duro o aproximado.`, pron:'RAF',
  uso:[`Puede describir una superficie no lisa, una situación difícil o una cifra aproximada: _a rough estimate_.`],
  ej:[[`The road is rough.`,`La carretera es áspera.`],[`I had a rough day.`,`Tuve un día duro.`]], prac:'vocabulary', rel:['tough','enough','though'] },
{ slug:'salmon', t:'salmon', tipo:'palabra',
  resp:`Salmón. La l no se pronuncia.`, pron:'SÁ-mon',
  uso:[`Es un tipo de pescado. Aunque se escribe con l, se pronuncia como si no estuviera.`],
  ej:[[`We had salmon for dinner.`,`Cenamos salmón.`],[`Salmon is rich in protein.`,`El salmón es rico en proteína.`]], prac:'vocabulary', rel:['vegetable','rough','thought'] },
{ slug:'vegetable', t:'vegetable', tipo:'palabra',
  resp:`Verdura o vegetal. La segunda sílaba suele reducirse al hablar.`, pron:'VÉYCH-ta-bol',
  uso:[`Es un sustantivo contable: _a vegetable_, _vegetables_. En conversación, la g no suena como una g española.`],
  ej:[[`Try to eat more vegetables.`,`Intenta comer más verduras.`],[`A carrot is a vegetable.`,`Una zanahoria es una verdura.`]], prac:'vocabulary', rel:['salmon','wednesday','usually'] },
{ slug:'wednesday', t:'Wednesday', tipo:'palabra',
  resp:`Miércoles. La d después de la e no se pronuncia.`, pron:'UÉNZ-dei',
  uso:[`Se escribe con mayúscula porque es un día de la semana. Usa _on Wednesday_ para hablar de ese día.`],
  ej:[[`The meeting is on Wednesday.`,`La reunión es el miércoles.`],[`I work from home every Wednesday.`,`Trabajo desde casa todos los miércoles.`]], prac:'vocabulary', rel:['february','hour','usually'] },
{ slug:'february', t:'February', tipo:'palabra',
  resp:`Febrero. La primera r suele ser muy suave o no sonar en habla rápida.`, pron:'FÉB-ru-e-ri',
  uso:[`Se escribe con mayúscula. En fechas estadounidenses es común decir _February fifth_.`],
  ej:[[`My birthday is in February.`,`Mi cumpleaños es en febrero.`],[`February has twenty-eight days.`,`Febrero tiene veintiocho días.`]], prac:'vocabulary', rel:['wednesday','hour','probably'] },
{ slug:'clothes', t:'clothes', tipo:'palabra',
  resp:`Ropa. La th no se pronuncia como en _think_.`, pron:'KLOUZ',
  uso:[`Es un sustantivo plural: _These clothes are new_. Para una prenda usa _clothing item_ o el nombre específico.`],
  ej:[[`My clothes are still wet.`,`Mi ropa todavía está mojada.`],[`She bought new clothes.`,`Ella compró ropa nueva.`]], prac:'vocabulary', rel:['busy','women','put-on'] },
{ slug:'world', t:'world', tipo:'palabra',
  resp:`Mundo. Combina el sonido de W con una r difícil para hispanohablantes.`, pron:'UÉRLD',
  uso:[`Puede hablar del planeta o de un ámbito: _the world_, _the world of work_.`],
  ej:[[`English is spoken around the world.`,`El inglés se habla en todo el mundo.`],[`The world is changing quickly.`,`El mundo está cambiando rápidamente.`]], prac:'vocabulary', rel:['word','girl','throughout'] },
{ slug:'girl', t:'girl', tipo:'palabra',
  resp:`Niña o chica. La vocal y la r forman un solo sonido.`, pron:'GUERL',
  uso:[`Se refiere normalmente a una niña o joven. Para una adulta, según el contexto, suele ser mejor _woman_.`],
  ej:[[`The girl is reading a book.`,`La niña está leyendo un libro.`],[`She was a shy girl.`,`Ella era una chica tímida.`]], prac:'vocabulary', rel:['world','women','clothes'] },
{ slug:'almond', t:'almond', tipo:'palabra',
  resp:`Almendra. La l suele ser muda en inglés estadounidense.`, pron:'Á-mon(d)',
  uso:[`Es una nuez comestible. En pronunciación estadounidense, muchas personas no marcan la l.`],
  ej:[[`I added almonds to my salad.`,`Agregué almendras a mi ensalada.`],[`Almond milk is popular.`,`La leche de almendras es popular.`]], prac:'vocabulary', rel:['salmon','vegetable','thought'] },
{ slug:'word', t:'word', tipo:'palabra',
  resp:`Palabra. Se parece a _world_, pero no tiene el sonido l.`, pron:'UÉRD',
  uso:[`Es un sustantivo contable: _a word_, _new words_. También aparece en _in other words_ (en otras palabras).`],
  ej:[[`I don't know that word.`,`No conozco esa palabra.`],[`Write the word here.`,`Escribe la palabra aquí.`]], prac:'vocabulary', rel:['world','were','thought'] },
{ slug:'were', t:'were', tipo:'gramatica',
  resp:`Eran o estaban. Es el pasado de _are_ para you, we y they.`, pron:'UER',
  uso:[`Usa _were_ con you, we y they: _They were happy_. También se usa en _If I were you_ para dar consejos hipotéticos.`],
  ej:[[`We were tired after the trip.`,`Estábamos cansados después del viaje.`],[`If I were you, I'd wait.`,`Si yo fuera tú, esperaría.`]], prac:'grammar', rel:['was-vs-were','werent','youre'] },
{ slug:'would', t:'would', tipo:'gramatica',
  resp:`Haría, sería o gustaría. Se usa para condicionales, cortesía y hábitos pasados.`, pron:'WUD',
  uso:[`Va seguido de verbo base: _would go_. En peticiones corteses: _Would you help me?_ Se contrae como _'d_.`],
  ej:[[`I would choose the blue one.`,`Yo elegiría el azul.`],[`Would you like some coffee?`,`¿Te gustaría un poco de café?`]], prac:'grammar', rel:['wouldnt','could','should'] },
{ slug:'could', t:'could', tipo:'gramatica',
  resp:`Podía, podría o pudiste. Es el pasado y una forma cortés de _can_.`, pron:'KUD',
  uso:[`Sirve para capacidad pasada, posibilidades y peticiones: _Could you repeat that?_ Va con verbo base.`],
  ej:[[`She could read at four.`,`Ella podía leer a los cuatro años.`],[`Could you speak more slowly?`,`¿Podrías hablar más despacio?`]], prac:'grammar', rel:['couldnt','would','should'] },
{ slug:'should', t:'should', tipo:'gramatica',
  resp:`Debería. Da consejos y expectativas.`, pron:'SHUD',
  uso:[`Después de _should_ va el verbo base: _You should rest_. Para el pasado usa _should have_ + participio.`],
  ej:[[`You should drink more water.`,`Deberías tomar más agua.`],[`The train should arrive soon.`,`El tren debería llegar pronto.`]], prac:'grammar', rel:['shouldnt','should-have','could'] },
{ slug:'stomach', t:'stomach', tipo:'palabra',
  resp:`Estómago. La ch suena como k, no como ch española.`, pron:'STÓ-mak',
  uso:[`Puede ser el órgano o la zona del abdomen. La expresión _have a stomachache_ significa tener dolor de estómago.`],
  ej:[[`My stomach hurts.`,`Me duele el estómago.`],[`I have a sensitive stomach.`,`Tengo un estómago sensible.`]], prac:'vocabulary', rel:['thought','tough','vegetable'] },
{ slug:'usually', t:'usually', tipo:'palabra',
  resp:`Usualmente, normalmente.`, pron:'IÚ-zhu-a-li',
  uso:[`Es un adverbio de frecuencia. Suele ir antes del verbo principal, pero después de _be_: _I usually walk_; _She is usually early_.`],
  ej:[[`I usually have coffee in the morning.`,`Normalmente tomo café en la mañana.`],[`He's usually on time.`,`Él normalmente llega puntual.`]], prac:'grammar', rel:['probably','actually','wednesday'] },
{ slug:'probably', t:'probably', tipo:'palabra',
  resp:`Probablemente. En habla rápida suele sonar con menos sílabas.`, pron:'PRÁ-ba-bli',
  uso:[`Expresa que algo es probable, pero no seguro. Normalmente va antes del verbo principal: _She'll probably call_.`],
  ej:[[`It will probably rain later.`,`Probablemente lloverá más tarde.`],[`She's probably at home.`,`Probablemente ella está en casa.`]], prac:'vocabulary', rel:['usually','literally','particularly'] },
{ slug:'literally', t:'literally', tipo:'palabra',
  resp:`Literalmente. Se usa para el sentido exacto de las palabras.`, pron:'LÍ-te-ra-li',
  uso:[`En uso cuidado significa "de manera literal": _I literally read every word_. En conversación algunas personas lo usan como intensificador.`],
  ej:[[`I literally missed the last bus.`,`Literalmente perdí el último bus.`],[`Don't take it literally.`,`No lo tomes literalmente.`]], prac:'vocabulary', rel:['actually','particularly','probably'] },
{ slug:'particularly', t:'particularly', tipo:'palabra',
  resp:`Particularmente, especialmente.`, pron:'par-TÍ-kiu-ler-li',
  uso:[`Destaca una cosa dentro de un grupo. Puede ir antes de un adjetivo o al final de una idea.`],
  ej:[[`I particularly like this song.`,`Me gusta particularmente esta canción.`],[`It's particularly useful for beginners.`,`Es especialmente útil para principiantes.`]], prac:'vocabulary', rel:['literally','probably','usually'] },
{ slug:'rural', t:'rural', tipo:'palabra',
  resp:`Rural, relacionado con el campo. Tiene dos sonidos r seguidos.`, pron:'RÚ-rəl',
  uso:[`Describe áreas fuera de las ciudades: _rural areas_, _rural communities_.`],
  ej:[[`She grew up in a rural area.`,`Ella creció en una zona rural.`],[`Rural roads can be narrow.`,`Las carreteras rurales pueden ser estrechas.`]], prac:'vocabulary', rel:['squirrel','world','girl'] },
{ slug:'squirrel', t:'squirrel', tipo:'palabra',
  resp:`Ardilla. Es una palabra famosa por su combinación de sonidos.`, pron:'SKUÍ-rəl',
  uso:[`Es un sustantivo contable. En Estados Unidos se suele oír dos sílabas claras: _squir-rel_.`],
  ej:[[`A squirrel ran up the tree.`,`Una ardilla subió corriendo al árbol.`],[`We saw squirrels in the park.`,`Vimos ardillas en el parque.`]], prac:'vocabulary', rel:['rural','world','queue'] },
{ slug:'queue', t:'queue', tipo:'palabra',
  resp:`Fila o cola. Solo se pronuncia la letra q.`, pron:'KIÚ',
  uso:[`Es más común en inglés británico. En Estados Unidos se dice más _line_: _stand in line_.`],
  ej:[[`We waited in a long queue.`,`Esperamos en una fila larga.`],[`There was a queue outside.`,`Había una fila afuera.`]], prac:'vocabulary', rel:['choir','colonel','hour'] },
{ slug:'choir', t:'choir', tipo:'palabra',
  resp:`Coro. La ch no suena como en _chair_.`, pron:'KUÁI-er',
  uso:[`Es un grupo de personas que canta. También puede referirse al espacio de una iglesia destinado al coro.`],
  ej:[[`She sings in the school choir.`,`Ella canta en el coro de la escuela.`],[`The choir sounded beautiful.`,`El coro sonó hermoso.`]], prac:'vocabulary', rel:['queue','colonel','thought'] },
{ slug:'colonel', t:'colonel', tipo:'palabra',
  resp:`Coronel. Su escritura no se parece a su pronunciación.`, pron:'KÉR-nəl',
  uso:[`Es un rango militar. Se usa con mayúscula antes de un nombre: _Colonel Smith_.`],
  ej:[[`The colonel spoke to the team.`,`El coronel habló con el equipo.`],[`Colonel Harris arrived early.`,`El coronel Harris llegó temprano.`]], prac:'vocabulary', rel:['queue','choir','genre'] },
{ slug:'genre', t:'genre', tipo:'palabra',
  resp:`Género, especialmente de música, cine o libros.`, pron:'ZHÁN-ra',
  uso:[`La g suena como la j francesa o la s de "vision". Se usa para clasificar obras: _a music genre_.`],
  ej:[[`What genre of music do you like?`,`¿Qué género de música te gusta?`],[`Comedy is my favorite genre.`,`La comedia es mi género favorito.`]], prac:'vocabulary', rel:['colonel','choir','queue'] },
{ slug:'yacht', t:'yacht', tipo:'palabra',
  resp:`Yate. La ch no se pronuncia.`, pron:'YOT',
  uso:[`Es una embarcación de recreo. Aunque empieza con y, su vocal se parece a la de _hot_.`],
  ej:[[`They rented a yacht for the day.`,`Ellos alquilaron un yate por el día.`],[`The yacht is in the harbor.`,`El yate está en el puerto.`]], prac:'vocabulary', rel:['thought','rough','queue'] },
{ slug:'heir', t:'heir', tipo:'palabra',
  resp:`Heredero o heredera. La h no se pronuncia.`, pron:'ER',
  uso:[`Es la persona que recibirá bienes o un título. Se usa _an heir_ porque empieza con sonido vocálico.`],
  ej:[[`He is the heir to the family business.`,`Él es el heredero del negocio familiar.`],[`She became the heir to the estate.`,`Ella se convirtió en la heredera de la propiedad.`]], prac:'vocabulary', rel:['honest','hour','island'] },
{ slug:'honest', t:'honest', tipo:'palabra',
  resp:`Honesto. La h es muda, por eso se dice _an honest person_.`, pron:'Á-nest',
  uso:[`Describe a alguien que dice la verdad o actúa con integridad. La forma adverbial es _honestly_.`],
  ej:[[`Be honest with me.`,`Sé honesto conmigo.`],[`She's an honest person.`,`Ella es una persona honesta.`]], prac:'vocabulary', rel:['heir','hour','actually'] },
{ slug:'hour', t:'hour', tipo:'palabra',
  resp:`Hora. La h es muda y se usa _an hour_.`, pron:'ÁU-er',
  uso:[`Es una unidad de sesenta minutos. Para horas exactas usa _at_: _at three o'clock_.`],
  ej:[[`The class lasts an hour.`,`La clase dura una hora.`],[`I'll be there in an hour.`,`Estaré allí en una hora.`]], prac:'vocabulary', rel:['heir','honest','wednesday'] },
{ slug:'island', t:'island', tipo:'palabra',
  resp:`Isla. La s es muda.`, pron:'ÁI-land',
  uso:[`Es una porción de tierra rodeada de agua. No se pronuncia como si tuviera s.`],
  ej:[[`They live on a small island.`,`Ellos viven en una isla pequeña.`],[`The island has beautiful beaches.`,`La isla tiene playas hermosas.`]], prac:'vocabulary', rel:['yacht','heir','world'] },
{ slug:'debt', t:'debt', tipo:'palabra',
  resp:`Deuda. La b no se pronuncia.`, pron:'DET',
  uso:[`Es dinero que se debe. Se usa _be in debt_ para decir tener deudas.`],
  ej:[[`He is trying to pay off his debt.`,`Él intenta pagar su deuda.`],[`Don't get into debt.`,`No te endeudes.`]], prac:'vocabulary', rel:['doubt','business','bought'] },
{ slug:'doubt', t:'doubt', tipo:'palabra',
  resp:`Duda o dudar. La b no se pronuncia.`, pron:'DÁUT',
  uso:[`Como verbo puede ir con _that_ o una pregunta indirecta: _I doubt that..._ Como sustantivo: _I have doubts_.`],
  ej:[[`I doubt that he knows.`,`Dudo que él sepa.`],[`There is no doubt about it.`,`No hay duda al respecto.`]], prac:'vocabulary', rel:['debt','thought','though'] },
{ slug:'sword', t:'sword', tipo:'palabra',
  resp:`Espada. La w no se pronuncia.`, pron:'SORD',
  uso:[`Es un arma con hoja larga. Aunque se escribe con w, empieza directamente con sonido s.`],
  ej:[[`The knight carried a sword.`,`El caballero llevaba una espada.`],[`The sword was very old.`,`La espada era muy antigua.`]], prac:'vocabulary', rel:['word','world','thought'] },
{ slug:'answer', t:'answer', tipo:'palabra',
  resp:`Respuesta o responder. La w no se pronuncia.`, pron:'ÁN-ser',
  uso:[`Como verbo: _answer a question_. Como sustantivo: _the answer_. No lleva _to_ antes de una pregunta directa.`],
  ej:[[`Do you know the answer?`,`¿Sabes la respuesta?`],[`Please answer my email.`,`Por favor responde mi correo.`]], prac:'vocabulary', rel:['sword','notice','word'] },
{ slug:'busy', t:'busy', tipo:'palabra',
  resp:`Ocupado. La pronunciación no tiene un sonido z escrito.`, pron:'BÍ-zi',
  uso:[`Se usa con _be_: _I'm busy_. Para decir que tienes mucho trabajo, también puedes decir _busy at work_.`],
  ej:[[`I'm busy this afternoon.`,`Estoy ocupado esta tarde.`],[`The restaurant is busy tonight.`,`El restaurante está concurrido esta noche.`]], prac:'vocabulary', rel:['business','usually','probably'] },
{ slug:'business', t:'business', tipo:'palabra',
  resp:`Negocio o negocios. La i del medio se reduce al hablar.`, pron:'BÍZ-nes',
  uso:[`Puede ser una empresa, la actividad comercial o un asunto personal: _mind your own business_.`],
  ej:[[`She owns a small business.`,`Ella tiene un pequeño negocio.`],[`Business is slow this month.`,`Los negocios están lentos este mes.`]], prac:'vocabulary', rel:['busy','debt','record'] },
{ slug:'women', t:'women', tipo:'palabra',
  resp:`Mujeres. Es el plural de _woman_ y cambia la vocal.`, pron:'UÍ-min',
  uso:[`_Woman_ es singular y _women_ es plural. No se pronuncian igual.`],
  ej:[[`The women are waiting outside.`,`Las mujeres están esperando afuera.`],[`Women and men joined the class.`,`Mujeres y hombres se unieron a la clase.`]], prac:'vocabulary', rel:['girl','were','clothes'] },

{ slug:'think', t:'think', tipo:'palabra',
  resp:`Pensar. Empieza con el sonido TH sordo, con la lengua entre los dientes.`, pron:'ZINK',
  uso:[`Puede ir seguido de _that_, una pregunta o _about_: _think about it_. El pasado es _thought_.`],
  ej:[[`I think you're right.`,`Creo que tienes razón.`],[`Think about your answer.`,`Piensa en tu respuesta.`]], prac:'vocabulary', rel:['thought','this','three'] },
{ slug:'this', t:'this', tipo:'palabra',
  resp:`Esto, esta o este. Empieza con TH sonoro.`, pron:'DÍS',
  uso:[`Se usa para algo cercano o actual: _this book_, _this is my friend_. El plural es _these_.`],
  ej:[[`This is my new phone.`,`Este es mi teléfono nuevo.`],[`I need this document.`,`Necesito este documento.`]], prac:'vocabulary', rel:['think','those','with'] },
{ slug:'three', t:'three', tipo:'palabra',
  resp:`Tres. Empieza con TH sordo, no con s ni t.`, pron:'ZRÍI',
  uso:[`Es el número 3. En una fecha o cantidad va antes del sustantivo plural: _three books_.`],
  ej:[[`I have three sisters.`,`Tengo tres hermanas.`],[`The meeting starts at three.`,`La reunión empieza a las tres.`]], prac:'vocabulary', rel:['think','this','thought'] },
{ slug:'those', t:'those', tipo:'palabra',
  resp:`Esos, esas o aquellos. Es el plural de _that_.`, pron:'DÓUZ',
  uso:[`Se refiere a cosas o personas que están más lejos: _those shoes_, _those are mine_.`],
  ej:[[`Those are my keys.`,`Esas son mis llaves.`],[`I like those pictures.`,`Me gustan esas fotos.`]], prac:'vocabulary', rel:['this','though','theyre'] },
{ slug:'scissors', t:'scissors', tipo:'palabra',
  resp:`Tijeras. Se usa en plural y la c no se pronuncia como k.`, pron:'SÍ-zers',
  uso:[`Aunque es un solo objeto, se dice _these scissors are_. Para una unidad puedes decir _a pair of scissors_.`],
  ej:[[`These scissors are sharp.`,`Estas tijeras están afiladas.`],[`I need a pair of scissors.`,`Necesito unas tijeras.`]], prac:'vocabulary', rel:['clothes','put-on','sword'] },
{ slug:'aisle', t:'aisle', tipo:'palabra',
  resp:`Pasillo, por ejemplo en un supermercado o avión. La s es muda.`, pron:'ÁIL',
  uso:[`Se usa para los pasillos entre filas: _the cereal aisle_, _an aisle seat_.`],
  ej:[[`The milk is in aisle five.`,`La leche está en el pasillo cinco.`],[`I prefer an aisle seat.`,`Prefiero un asiento de pasillo.`]], prac:'vocabulary', rel:['queue','thought','through'] },
{ slug:'with', t:'with', tipo:'palabra',
  resp:`Con. Empieza con TH sonoro.`, pron:'UÍD',
  uso:[`Indica compañía, instrumento o relación: _with friends_, _cut with a knife_.`],
  ej:[[`I'm here with my brother.`,`Estoy aquí con mi hermano.`],[`Write with a pen.`,`Escribe con un bolígrafo.`]], prac:'vocabulary', rel:['without','this','think'] },
{ slug:'without', t:'without', tipo:'palabra',
  resp:`Sin. Es lo contrario de _with_.`, pron:'ui-DÁUT',
  uso:[`Va antes de un sustantivo o verbo en -ing: _without money_, _without saying goodbye_.`],
  ej:[[`I can't live without music.`,`No puedo vivir sin música.`],[`She left without saying goodbye.`,`Ella se fue sin despedirse.`]], prac:'grammar', rel:['with','throughout','wont'] },
{ slug:'very', t:'very', tipo:'palabra',
  resp:`Muy. La v se hace con los dientes y el labio inferior.`, pron:'VÉ-ri',
  uso:[`Intensifica adjetivos y adverbios: _very good_, _very slowly_. No suele usarse con comparativos como _better_.`],
  ej:[[`This coffee is very hot.`,`Este café está muy caliente.`],[`She speaks very clearly.`,`Ella habla muy claramente.`]], prac:'vocabulary', rel:['voice','vowel','view'] },
{ slug:'voice', t:'voice', tipo:'palabra',
  resp:`Voz. Empieza con v, no con b.`, pron:'VÓIS',
  uso:[`Es el sonido que produce una persona al hablar o cantar. También existe la expresión _voice an opinion_.`],
  ej:[[`I recognize your voice.`,`Reconozco tu voz.`],[`Speak in a clear voice.`,`Habla con una voz clara.`]], prac:'vocabulary', rel:['very','vowel','view'] },
{ slug:'vowel', t:'vowel', tipo:'palabra',
  resp:`Vocal. La primera letra es v, no b.`, pron:'VÁU-el',
  uso:[`Las vocales inglesas son a, e, i, o y u; a veces y. Es útil para reglas como _a_ o _an_.`],
  ej:[[`A is a vowel.`,`A es una vocal.`],[`This word starts with a vowel sound.`,`Esta palabra empieza con un sonido vocal.`]], prac:'vocabulary', rel:['very','voice','a-vs-an'] },
{ slug:'view', t:'view', tipo:'palabra',
  resp:`Vista, panorama u opinión.`, pron:'VIÚ',
  uso:[`Como sustantivo puede ser lo que ves desde un lugar o un punto de vista: _a great view_, _my view is..._`],
  ej:[[`The room has a great view.`,`La habitación tiene una gran vista.`],[`In my view, it's too expensive.`,`En mi opinión, es demasiado caro.`]], prac:'vocabulary', rel:['very','voice','queue'] },
{ slug:'live', t:'live', tipo:'palabra',
  resp:`Vivir o en vivo. La pronunciación cambia según el significado.`, pron:'LIV (vivir) / LÁIV (en vivo)',
  uso:[`Como verbo es _live_ /liv/: _I live here_. Como adjetivo significa "en vivo" y se pronuncia /laiv/: _live music_.`],
  ej:[[`I live near the station.`,`Vivo cerca de la estación.`],[`We watched live music.`,`Vimos música en vivo.`]], prac:'vocabulary', rel:['leave','record','read'] },
{ slug:'leave', t:'leave', tipo:'palabra',
  resp:`Salir, irse, dejar o permitir.`, pron:'LÍIV',
  uso:[`_Leave_ puede significar irse de un lugar o dejar algo allí: _leave home_, _leave your bag here_.`],
  ej:[[`We need to leave now.`,`Necesitamos irnos ahora.`],[`Leave your shoes by the door.`,`Deja tus zapatos junto a la puerta.`]], prac:'vocabulary', rel:['live','read','take-off'] },
{ slug:'read', t:'read', tipo:'palabra',
  resp:`Leer. Se escribe igual en presente y pasado, pero cambia la vocal.`, pron:'RÍID (presente) / RÉD (pasado)',
  uso:[`En presente: _I read every day_ /riid/. En pasado: _I read it yesterday_ /red/.`],
  ej:[[`I read before bed.`,`Leo antes de dormir.`],[`She read the email yesterday.`,`Ella leyó el correo ayer.`]], prac:'vocabulary', rel:['thought','bought','taught'] },
{ slug:'bought', t:'bought', tipo:'palabra',
  resp:`Compré o compró. Es el pasado y participio de _buy_.`, pron:'BOT',
  uso:[`Se usa para compras terminadas: _I bought a ticket_. El presente es _buy_, no _bought_.`],
  ej:[[`I bought this jacket online.`,`Compré esta chaqueta en línea.`],[`They bought a new car.`,`Ellos compraron un carro nuevo.`]], prac:'grammar', rel:['brought','caught','thought'] },
{ slug:'brought', t:'brought', tipo:'palabra',
  resp:`Traje o trajo. Es el pasado y participio de _bring_.`, pron:'BROT',
  uso:[`Indica movimiento hacia el hablante o destino: _She brought her passport_.`],
  ej:[[`She brought some snacks.`,`Ella trajo algunos bocadillos.`],[`I brought my laptop to class.`,`Llevé mi portátil a clase.`]], prac:'grammar', rel:['bring-vs-take','bought','caught'] },
{ slug:'caught', t:'caught', tipo:'palabra',
  resp:`Atrapé, cogí o entendí. Es el pasado y participio de _catch_.`, pron:'KOT',
  uso:[`Puede ser atrapar algo, tomar un transporte o captar una idea: _catch a ball_, _catch a bus_, _catch what you said_.`],
  ej:[[`He caught the ball.`,`Él atrapó la pelota.`],[`I caught the last train.`,`Tomé el último tren.`]], prac:'grammar', rel:['bought','brought','taught'] },
{ slug:'taught', t:'taught', tipo:'palabra',
  resp:`Enseñé o enseñó. Es el pasado y participio de _teach_.`, pron:'TOT',
  uso:[`Se usa para explicar o enseñar una habilidad: _My teacher taught us English_.`],
  ej:[[`My mother taught me to cook.`,`Mi mamá me enseñó a cocinar.`],[`He taught English for years.`,`Él enseñó inglés durante años.`]], prac:'grammar', rel:['thought','caught','read'] },

{ slug:'wake-up', t:'wake up', tipo:'phrasal',
  resp:`Despertarse o despertar a alguien.`, pron:'UÉIK AP',
  uso:[`Puede ser intransitivo: _I wake up at seven_. Con una persona u objeto es separable: _Wake me up_, no _wake up me_.`],
  ej:[[`I wake up early on Mondays.`,`Me despierto temprano los lunes.`],[`Please wake me up at six.`,`Por favor despiértame a las seis.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['get-up','put-on','take-off'] },
{ slug:'get-up', t:'get up', tipo:'phrasal',
  resp:`Levantarse de la cama o ponerse de pie.`, pron:'GUET AP',
  uso:[`Después de despertarte normalmente _get up_. También puede significar ponerse de pie: _Get up and stretch_.`],
  ej:[[`I get up at seven every day.`,`Me levanto a las siete todos los días.`],[`He got up from his chair.`,`Él se levantó de su silla.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['wake-up','put-on','take-off'] },
{ slug:'turn-on', t:'turn on', tipo:'phrasal',
  resp:`Encender un aparato.`, pron:'TÉRN ON',
  uso:[`Es separable: _turn on the light_ o _turn the light on_. Con pronombre, va en medio: _turn it on_.`],
  ej:[[`Turn on the lights, please.`,`Enciende las luces, por favor.`],[`Can you turn it on?`,`¿Puedes encenderlo?`]], prac:'vocabulary', art:'phrasal-verbs', rel:['turn-off','put-on','take-off'] },
{ slug:'turn-off', t:'turn off', tipo:'phrasal',
  resp:`Apagar un aparato.`, pron:'TÉRN OF',
  uso:[`Es el contrario de _turn on_ y también es separable: _turn the TV off_, _turn it off_.`],
  ej:[[`Turn off the TV before bed.`,`Apaga el televisor antes de dormir.`],[`Don't forget to turn it off.`,`No olvides apagarlo.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['turn-on','put-on','wake-up'] },
{ slug:'pick-up', t:'pick up', tipo:'phrasal',
  resp:`Recoger, levantar o mejorar, según el contexto.`, pron:'PIK AP',
  uso:[`Puede significar levantar algo, recoger a una persona en carro o mejorar: _pick up the phone_, _pick me up_, _business picked up_.`],
  ej:[[`I'll pick you up at eight.`,`Pasaré por ti a las ocho.`],[`Pick up your bag.`,`Recoge tu bolsa.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['put-on','take-off','look-after'] },
{ slug:'put-on', t:'put on', tipo:'phrasal',
  resp:`Ponerse ropa o encender algo.`, pron:'PUT ON',
  uso:[`Con ropa, significa vestir algo: _put on a coat_. Es separable y con pronombre va en medio: _put it on_.`],
  ej:[[`Put on your jacket.`,`Ponte tu chaqueta.`],[`She put on some music.`,`Ella puso música.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['take-off','turn-on','pick-up'] },
{ slug:'take-off', t:'take off', tipo:'phrasal',
  resp:`Quitarse ropa o despegar un avión.`, pron:'TÉIK OF',
  uso:[`Para ropa es separable: _take off your shoes_. Para aviones no: _The plane took off_.`],
  ej:[[`Take off your shoes here.`,`Quítate los zapatos aquí.`],[`The plane took off on time.`,`El avión despegó a tiempo.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['put-on','turn-off','get-up'] },
{ slug:'look-after', t:'look after', tipo:'phrasal',
  resp:`Cuidar de alguien o algo.`, pron:'LUK ÁF-ter',
  uso:[`Va seguido de la persona o cosa que recibe cuidado: _look after the children_. No se separa.`],
  ej:[[`Can you look after my dog?`,`¿Puedes cuidar a mi perro?`],[`She looks after her younger brother.`,`Ella cuida a su hermano menor.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['look-for','pick-up','give-up'] },
{ slug:'run-out-of', t:'run out of', tipo:'phrasal',
  resp:`Quedarse sin algo.`, pron:'RAN ÁUT ov',
  uso:[`Se usa con cosas que se terminan: _run out of time_, _run out of milk_. El sujeto es quien se queda sin ello.`],
  ej:[[`We've run out of milk.`,`Nos quedamos sin leche.`],[`Don't run out of time.`,`No te quedes sin tiempo.`]], prac:'vocabulary', art:'phrasal-verbs', rel:['look-for','give-up','get'] },

{ slug:'eventually', t:'eventually', tipo:'palabra', comun:true,
  resp:`Finalmente, tarde o temprano. No significa "eventualmente" en español.`, pron:'i-VÉN-chu-a-li',
  uso:[`Habla de un resultado que ocurre después de un tiempo: _Eventually, we found a solution_. Para "posiblemente", usa _possibly_ o _maybe_.`],
  ej:[[`Eventually, the rain stopped.`,`Finalmente, la lluvia paró.`],[`She eventually found a new job.`,`Ella finalmente encontró un trabajo nuevo.`]], prac:'vocabulary', rel:['actually','probably','throughout'] },
{ slug:'chaos', t:'chaos', tipo:'palabra',
  resp:`Caos. La ch suena como k.`, pron:'KÉI-os',
  uso:[`Describe una situación sin orden ni control. Se usa sin artículo en expresiones como _in chaos_.`],
  ej:[[`The office was in chaos.`,`La oficina era un caos.`],[`Traffic caused chaos downtown.`,`El tráfico causó caos en el centro.`]], prac:'vocabulary', rel:['thought','throughout','busy'] },
{ slug:'subtle', t:'subtle', tipo:'palabra',
  resp:`Sutil. La b es muda.`, pron:'SÁ-təl',
  uso:[`Describe algo leve o difícil de notar: _a subtle difference_, _a subtle change_.`],
  ej:[[`There is a subtle difference.`,`Hay una diferencia sutil.`],[`Her perfume has a subtle smell.`,`Su perfume tiene un olor sutil.`]], prac:'vocabulary', rel:['notice','thought','doubt'] },
{ slug:'whistle', t:'whistle', tipo:'palabra',
  resp:`Silbar o silbato. La t es muda.`, pron:'UÍ-səl',
  uso:[`Como verbo es hacer un silbido; como sustantivo, un silbato o el sonido que produce.`],
  ej:[[`He can whistle very loudly.`,`Él puede silbar muy fuerte.`],[`The referee blew the whistle.`,`El árbitro hizo sonar el silbato.`]], prac:'vocabulary', rel:['three','thought','sword'] },
{ slug:'realize', t:'realize', tipo:'palabra', comun:true,
  resp:`Darse cuenta, comprender de pronto.`, pron:'RÍ-a-laiz',
  uso:[`No suele significar "realizar" una actividad. Usa _do_, _make_ o _carry out_ según el caso.`],
  ej:[[`I didn't realize it was so late.`,`No me di cuenta de que era tan tarde.`],[`She realized her mistake.`,`Ella se dio cuenta de su error.`]], prac:'vocabulary', rel:['notice','actually','thought'] },
{ slug:'notice', t:'notice', tipo:'palabra',
  resp:`Notar o aviso.`, pron:'NÓU-tis',
  uso:[`Como verbo es percibir algo: _notice a change_. Como sustantivo puede ser un aviso escrito.`],
  ej:[[`Did you notice the difference?`,`¿Notaste la diferencia?`],[`I didn't notice the sign.`,`No noté el letrero.`]], prac:'vocabulary', rel:['realize','thought','answer'] },
{ slug:'pretend', t:'pretend', tipo:'palabra', comun:true,
  resp:`Fingir. No significa "pretender" en el sentido de tener intención.`, pron:'pri-TÉND',
  uso:[`Se usa con _to_ + verbo o con _that_: _pretend to be asleep_. Para tener intención usa _intend_ o _plan_.`],
  ej:[[`The child pretended to be a doctor.`,`El niño fingió ser médico.`],[`Don't pretend that nothing happened.`,`No finjas que no pasó nada.`]], prac:'vocabulary', rel:['realize','actually','thought'] },
{ slug:'resume', t:'resume', tipo:'palabra',
  resp:`Reanudar o currículum, según la pronunciación y el contexto.`, pron:'ri-ZÚM (reanudar) / RÉ-zu-mei (currículum)',
  uso:[`Como verbo, _resume_ significa continuar después de una pausa. En Estados Unidos, _résumé_ es un currículum, aunque a menudo se escribe sin acentos.`],
  ej:[[`The meeting will resume at two.`,`La reunión se reanudará a las dos.`],[`Send your resume by email.`,`Envía tu currículum por correo.`]], prac:'vocabulary', rel:['record','probably','hour'] },
{ slug:'record', t:'record', tipo:'palabra',
  resp:`Grabar o registro. La sílaba fuerte cambia según sea verbo o sustantivo.`, pron:'ri-KÓRD (verbo) / RÉ-kord (sustantivo)',
  uso:[`Como verbo: _record a video_. Como sustantivo: _keep a record_. El cambio de acento distingue los dos usos.`],
  ej:[[`Please record the lesson.`,`Por favor graba la lección.`],[`She broke the school record.`,`Ella rompió el récord de la escuela.`]], prac:'vocabulary', rel:['resume','voice','live'] }
];
