// Genera mini-lecciones.js (los temas de la tarjeta "Siguiente refuerzo" del
// inicio) a partir de los temas reales de GRAMMAR_BANK en data.js. Asi
// index.html no tiene que descargar todo data.js (casi 900 KB) solo para
// mostrar un tema.
// Uso (desde la carpeta del proyecto):  node tools/generar_mini_lecciones.js
//
// Cada tema de data.js se muestra con una etiqueta corta (maximo ~17
// caracteres: en celular la tarjeta es angosta y una etiqueta mas larga
// la hace crecer y pisar la ficha de Leo AI). Si agregas un tema nuevo en
// data.js, el script avisa y lo incluye con su nombre sin parentesis.
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.join(__dirname, '..');
const ctx = {};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root, 'data.js'), 'utf8') + '\n;this.GB = GRAMMAR_BANK;', ctx);

const LABELS = {
  'Los números (1-10)': 'Números 1-10',
  'Plural: agregar "-s"': 'Plural: -s',
  '"This is..." (esto es...)': 'This is...',
  'Los colores': 'Colores',
  'Preguntas simples: "What is this?"': 'What is this?',
  'Yes / No básico': 'Yes / No',
  'Los días de la semana': 'Días de la semana',
  'Adjetivos posesivos simples (my / your)': 'my / your',
  'Borrow vs Lend (prestar)': 'borrow / lend',
  'Good vs Well': 'good / well',
  'He / She / It (pronombres)': 'he / she / it',
  'Is / Are (singular y plural)': 'is / are',
  'His / Her (posesivos simples)': 'his / her',
  'Pronombres objeto (me / you / him / her / it / us / them)': 'me / him / them',
  'Preposiciones de movimiento (to / into / from)': 'to / into / from',
  'This / These': 'this / these',
  'Do / Does': 'do / does',
  'Verbo "have" (tengo / tienes / tiene)': 'have / has',
  'Verbo "to be": am / is / are': 'am / is / are',
  '"To be" en pasado: was / were': 'was / were',
  'Números parecidos que confunden (13 vs 30, 14 vs 40...)': '13 vs 30',
  'Verbo to be, have y there is/are': 'there is / are',
  'Presente simple y "to be"': 'Presente simple',
  'There / Their / They\'re': 'their / they\'re',
  'A / An': 'a / an',
  'In / On / At': 'in / on / at',
  'Some / Any': 'some / any',
  'This / That / These / Those': 'this / that',
  'Question words (What / Where / When / Who)': 'what / where',
  'Adverbios de frecuencia (always / usually / sometimes / never)': 'always / never',
  'Can / Can\'t (habilidad)': 'can / can\'t',
  'Posesivos (my / your / his / her / our / their)': 'our / their',
  'Presente continuo (I am ___ing)': 'I am ___ing',
  'Comparativos (-er / more ... than)': '-er / more than',
  'Pasado simple con verbos regulares (-ed)': 'Pasado en -ed',
  'Preguntas con Do/Does en presente simple': 'Preguntas con do',
  'Its vs It\'s': 'its / it\'s',
  'Then vs Than': 'then / than',
  '"Your" vs "You\'re"': 'your / you\'re',
  '"To" vs "Too" vs "Two"': 'to / too / two',
  'Sustantivos contables e incontables': 'Contables',
  'Secuenciadores (first, then, after that, finally)': 'first, then...',
  'Much / Many': 'much / many',
  'Pasado simple con verbos irregulares': 'Pasado irregular',
  'By vs Until': 'by / until',
  'A little / Little / A few / Few': 'little / few',
  'Condicionales, comparativos y presente perfecto': 'Presente perfecto',
  'Past Perfect': 'Past perfect',
  '"Used to"': 'used to',
  'Present Perfect vs Past Simple': 'Perfect vs Past',
  'Since / For': 'since / for',
  'Conditionals (tipo 1 y 2)': 'Condicionales',
  'Reported Speech': 'Reported speech',
  'Voz pasiva (presente y pasado simple)': 'Voz pasiva',
  'Verbos modales de obligación (must / have to / should)': 'must / should',
  'Will vs Going to (futuro)': 'will / going to',
  'Gerundios vs infinitivos (like doing / want to do)': 'doing / to do',
  'Cláusulas relativas (who / which / that)': 'who / which',
  'Phrasal verbs comunes (look for / give up / find out)': 'Phrasal verbs',
  'Verbos modales de posibilidad (may / might / could)': 'may / might',
  'Cuantificadores (a lot of / much / many / few / little)': 'a lot of',
  'Who vs Whom': 'who / whom',
  'Affect vs Effect': 'affect / effect',
  '"Say" vs "Tell"': 'say / tell',
  '"Fewer" vs "Less"': 'fewer / less',
  '"Advice" vs "Advise"': 'advice / advise',
  'Comparativos de igualdad (as...as)': 'as ... as',
  'Verbos causativos (have something done)': 'have it done',
  'Actually / Currently': 'actually / currently',
  'Despite / Although / Instead of': 'despite / although',
  'Question tags (¿verdad? / ¿no es así?)': 'Question tags',
  'As vs Like': 'as / like',
  'By vs Until (en el trabajo)': 'by / until',
  'Wish, estilo indirecto y pasado perfecto': 'I wish...',
  'Condicional tipo 3': 'Condicional 3',
  'Inversiones enfáticas': 'Inversiones',
  'Conectores avanzados': 'Conectores',
  'Preposiciones sutiles': 'Preposiciones',
  'Cláusulas relativas reducidas': 'Relativas cortas',
  'Formal vs natural / matices': 'Formal / natural',
  'Wish / If only': 'wish / if only',
  'Condicionales mixtos': 'Condicional mixto',
  'Subjuntivo formal (It is essential that...)': 'Subjuntivo formal',
  'Colocaciones avanzadas (make vs do)': 'make / do',
  'Discurso indirecto con matices': 'Estilo indirecto',
  'Enfatizadores y hedging (arguably, tend to, likely)': 'tend to / likely',
  'Participios como adjetivos (-ed vs -ing)': '-ed / -ing',
  'Oraciones enfáticas con "It is... that" (cleft sentences)': 'It is ... that',
  'Quiet vs Quite vs Quit': 'quiet / quite',
  'Farther vs Further': 'farther / further',
  '"Lose" vs "Loose"': 'lose / loose',
  '"Beside" vs "Besides"': 'beside / besides',
  '"Lay" vs "Lie"': 'lay / lie',
  'Modales perfectos (must have been / should have gone)': 'must have been',
  'Who / Whom': 'who / whom',
  'Despite vs In spite of vs Even though': 'in spite of',
  'Voz pasiva con modales (should be / must have been)': 'should be done',
  'Bring vs Take': 'bring / take',
  'Inversión, would rather y it\'s high time': 'would rather',
};

// Microexplicacion de cada etiqueta (la ve la persona bajo "Siguiente
// refuerzo"). Debe ser MUY corta (~42 caracteres max), frase natural y no formula: en celular la tarjeta
// solo da para 2 renglones. Donde fue posible se reutiliza la explicacion que
// ya existe en data.js.
const TIPS = {
  'Números 1-10': 'Del 1 al 10: one, two, three, four...',
  'Plural: -s': 'Para más de uno, agrega -s: cat → cats.',
  'This is...': 'Usa “this” para señalar una cosa cerca.',
  'Colores': 'El color va antes: a red car.',
  'What is this?': 'Respondes con “It\'s a...”: It\'s a book.',
  'Yes / No': 'Responde “Yes, it is” o “No, it isn\'t”.',
  'Días de la semana': 'Los días llevan mayúscula: Monday.',
  'my / your': 'Usa “my” para lo tuyo: my book.',
  'borrow / lend': 'Borrow: pedir prestado. Lend: dar.',
  'good / well': 'Good describe algo; well, cómo lo haces.',
  'he / she / it': 'Usa “it” para animales y cosas.',
  'is / are': 'Usa “are” con más de uno: they are.',
  'his / her': 'His es de él; her, de ella.',
  'me / him / them': 'Van después del verbo: help me.',
  'to / into / from': 'Usa “into” para entrar a algo.',
  'this / these': 'Usa “these” si hay más de uno.',
  'do / does': 'Con he/she/it usamos does.',
  'have / has': 'Con he/she/it usamos has: she has a car.',
  'am / is / are': '“I” siempre va con “am”: I am happy.',
  'was / were': 'Con you/we/they usamos were.',
  '13 vs 30': 'Termina en -teen (13) o en -ty (30).',
  'there is / are': 'Uno: there is. Varios: there are.',
  'Presente simple': 'Con he/she/it, el verbo lleva -s: works.',
  'their / they\'re': 'Their es “de ellos”; they\'re, “ellos son”.',
  'a / an': 'Usa an antes de un sonido vocal.',
  'in / on / at': 'Usamos in para estar dentro de algo.',
  'some / any': 'Usa any en negativas y preguntas.',
  'this / that': 'This es cerca; that, lejos.',
  'what / where': 'Where pregunta por un lugar.',
  'always / never': 'Van antes del verbo: I always work.',
  'can / can\'t': 'Can no cambia: he can, she can.',
  'our / their': 'Our es “nuestro”; their, “de ellos”.',
  'I am ___ing': 'Para algo que pasa ahora: I am eating.',
  '-er / more than': 'Corto: taller. Largo: more beautiful.',
  'Pasado en -ed': 'En pasado regular, agrega -ed: watched.',
  'Preguntas con do': 'Con she/he/it preguntas con Does.',
  'its / it\'s': 'It\'s quiere decir “it is”.',
  'then / than': 'Than sirve para comparar: taller than.',
  'your / you\'re': 'You\'re quiere decir “you are”.',
  'to / too / two': 'Too quiere decir “demasiado”.',
  'Contables': 'Si no se cuenta (water), usa much.',
  'first, then...': 'Ordena pasos: first, then, finally.',
  'much / many': 'Many va con cosas que cuentas.',
  'Pasado irregular': 'Algunos cambian por completo: go → went.',
  'by / until': 'By es “a más tardar”: by Friday.',
  'little / few': 'A little es “un poco” (algo hay).',
  'Presente perfecto': 'Algo que ya pasó: I have seen it.',
  'Past perfect': 'Algo que pasó antes de otro pasado.',
  'used to': 'Used to es un hábito del pasado.',
  'Perfect vs Past': 'Con yet y already: presente perfecto.',
  'since / for': 'Since es desde cuándo; for, duración.',
  'Condicionales': 'Si es posible: If it rains, I\'ll stay.',
  'Reported speech': 'Al contar lo dicho, will pasa a would.',
  'Voz pasiva': 'Sin decir quién lo hizo: it was made.',
  'must / should': 'Must es obligación; should, consejo.',
  'will / going to': 'Going to es para planes ya decididos.',
  'doing / to do': 'Después de want va to: want to go.',
  'who / which': 'Who es para personas; which, para cosas.',
  'Phrasal verbs': 'Give up significa rendirse.',
  'may / might': 'Might dice que algo es posible.',
  'a lot of': 'A lot of: con contables e incontables.',
  'who / whom': 'Who hace la acción; whom la recibe.',
  'affect / effect': 'Affect es un verbo; effect, un resultado.',
  'say / tell': 'Tell lleva persona: tell me; say, no.',
  'fewer / less': 'Fewer va con cosas que cuentas.',
  'advice / advise': 'Advice es el consejo; advise, aconsejar.',
  'as ... as': 'Para decir “tan... como”: as tall as.',
  'have it done': 'Cuando otro lo hace por ti: have it fixed.',
  'actually / currently': 'Actually quiere decir “en realidad”.',
  'despite / although': 'Despite va con un sustantivo o -ing.',
  'Question tags': 'Se agrega al final: It\'s cold, isn\'t it?',
  'as / like': 'Like compara; as dice qué papel tienes.',
  'I wish...': 'Deseo irreal: I wish I had time.',
  'Condicional 3': 'Algo que no pasó: If I had known...',
  'Inversiones': 'Para dar énfasis: Never have I seen it.',
  'Conectores': 'Nevertheless significa “sin embargo”.',
  'Preposiciones': 'Se dice depend on, no depend of.',
  'Relativas cortas': 'Se puede acortar: the man standing there.',
  'Formal / natural': 'En formal, purchase; al hablar, buy.',
  'wish / if only': 'If only expresa un deseo fuerte.',
  'Condicional mixto': 'Une un pasado con un presente.',
  'Subjuntivo formal': 'En formal: It\'s vital that he be here.',
  'make / do': 'Make es crear; do, actividades.',
  'Estilo indirecto': 'Al reportar, el tiempo retrocede un paso.',
  'tend to / likely': 'Tend to quiere decir “suele”.',
  '-ed / -ing': '-ing describe lo que causa: surprising.',
  'It is ... that': 'Sirve para enfatizar: It was Ana who...',
  'quiet / quite': 'Quite significa “bastante”.',
  'farther / further': 'Farther es distancia física.',
  'lose / loose': 'Lose es perder; loose, flojo.',
  'beside / besides': 'Beside es “al lado de”.',
  'lay / lie': 'Lie es recostarse uno mismo.',
  'must have been': 'Suponer algo pasado: must have been.',
  'in spite of': 'In spite of significa “a pesar de”.',
  'should be done': 'Dar un consejo: it should be done.',
  'bring / take': 'Take es llevar lejos; bring, traer.',
  'would rather': 'Would rather quiere decir “preferiría”.',
};

const topics = new Set();
Object.keys(ctx.GB).forEach(level => ctx.GB[level].forEach(variant => variant.forEach(t => topics.add(t.topic))));
const pool = new Map();
topics.forEach(t => {
  if(!LABELS[t]) console.warn('Tema sin etiqueta corta (usando nombre sin parentesis):', t);
  const label = LABELS[t] || t.replace(/\s*\(.*?\)/g, '').replace(/"/g, '');
  if(!TIPS[label]) console.warn('Etiqueta sin microexplicacion:', label);
  if(!pool.has(label)) pool.set(label, TIPS[label] || '');
});
const list = Array.from(pool, ([label, tip]) => [label, tip]);
const out = '/* Archivo generado por tools/generar_mini_lecciones.js a partir de data.js.\n   No editar a mano: edita las etiquetas y microexplicaciones en ese script y vuelve a correrlo. */\n' +
  'const MINI_LESSONS = ' + JSON.stringify(list) + ';\n';
fs.writeFileSync(path.join(root, 'mini-lecciones.js'), out);
console.log('mini-lecciones.js:', list.length, 'temas,', out.length, 'bytes');
